import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ru' | 'en' | 'lv';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Church Info
    'church.name': 'Храм Спасения',
    'church.officialName': 'Rīgas Misionāru baptistu draudze',
    'church.shortName': 'Евангельская церковь',
    'church.tagline': 'Евангельская церковь в Риге',
    'church.welcome': 'Добро пожаловать в наш дом! Мы — живая община верующих, объединённых любовью ко Христу.',
    'church.heroWelcome': 'Ощутите Божье присутствие в церкви в это воскресенье.',
    'church.shortDesc': 'Евангельская христианская церковь, служащая Риге с любовью и верой.',
    'church.serviceSunday': 'Воскресенье 11:00',
    'church.serviceWednesday': 'Среда 18:00',
    'church.serviceLanguages': 'Русский и Латышский',
    'church.planVisit': 'Посетить нас',
    'church.watchLive': 'Смотреть онлайн',

    // Hero
    'hero.comeAndSee': 'Приди и Увидь',
    'hero.changed': 'Изменённые',
    'hero.word.hearts': 'сердца',
    'hero.word.lives': 'жизни',
    'hero.word.relationships': 'отношения',
    'hero.word.minds': 'умы',
    'hero.word.personality': 'характеры',
    'hero.word.values': 'ценности',
    'hero.word.eternities': 'вечности',
    'hero.changing.hearts': 'Изменённые сердца',
    'hero.changing.lives': 'Изменённые жизни',
    'hero.changing.relationships': 'Изменённые отношения',
    'hero.changing.minds': 'Изменённое мышление',
    'hero.changing.personality': 'Изменённый характер',
    'hero.changing.values': 'Изменённые ценности',
    'hero.changing.eternities': 'Изменённые вечности',

    // Navigation
    'nav.about': 'О нас',
    'nav.history': 'История',
    'nav.events': 'События',
    'nav.ministries': 'Служения',
    'nav.testimonies': 'Свидетельства',
    'nav.contacts': 'Контакты',
    'nav.donations': 'Пожертвования',
    'nav.program': 'Программа',
    'nav.calendar': 'Календарь',
    'nav.team': 'Команда',
    'nav.register': 'Регистрация',

    // About Section
    'about.title': 'О нас',
    'about.subtitle': 'Познакомьтесь с нашей церковью',
    'about.intro': 'Храм Спасения — место, где люди духовно крепнут и учатся распространению Евангелия.',
    'about.getToKnowUs': 'Познакомиться с нами',
    'about.vision.title': 'Наше Видение',
    'about.vision.text': 'Храм Спасения прославляет Бога, создавая и взращивая учеников, получивших полное наставление Христа в Латгальском регионе Риги, которые в свою очередь создают новых учеников, что приведет к открытию новой церкви в Латвии.',
    'about.vision.textShort': 'Храм Спасения прославляет Бога, создавая и взращивая учеников, получивших полное наставление Христа в Латгальском регионе Риги, которые в свою очередь создают новых учеников, что приведет к открытию новой церкви в Латвии.',
    'about.values.title': 'Наши Ценности',
    'about.values.christ.title': 'Христос — наш центр',
    'about.values.christ.paragraph': 'Христос — наш центр и фокус во всем, что мы делаем. Мы помним, кто Он был и что Он сделал, а также то, что Он делает сейчас через Духа Святого.',
    'about.values.bible.title': 'Библия — наша истина',
    'about.values.bible.paragraph': 'Слово Божье — основа нашей веры. Евангелие и все книги Библии направляют нашу жизнь и служение.',
    'about.values.discipleship.title': 'Ученичество',
    'about.values.discipleship.paragraph': 'Мы растём через наставничество и общение с целью духовного роста, помогая друг другу становиться зрелыми последователями Христа.',
    'about.values.mission.title': 'Миссия',
    'about.values.mission.paragraph': 'Мы делимся благой вестью словом и делом, проявляя Божью любовь в практическом служении окружающим.',
    'about.mission.title': 'Наша Миссия',
    'about.mission.text': 'Храм Спасения — место, где люди духовно крепнут и учатся распространению Евангелия.',
    'about.historyButton': 'Узнать историю церкви',

    // Statistics
    'statistics.title': 'Наша Община',
    'statistics.subtitle': 'Мы — семья верующих разных возрастов',
    'statistics.total': 'Всего членов',
    'statistics.members.hover': 'Мы — разнообразная община из 150 человек всех возрастов и жизненных путей. Дети, молодёжь, семьи и старшее поколение вместе прославляют Бога.',
    'statistics.pastYear.title': 'Наша церковь за прошлый год в цифрах',
    'statistics.history.title': 'За всю историю церкви',
    'statistics.history.baptisms': 'Крещений',
    'statistics.history.sundaySchool': 'Детей в воскресной школе',
    'statistics.history.summerCamps': 'Участников летних лагерей',
    'statistics.history.families': 'Семей получили помощь',
    'statistics.history.childrenCare': 'Детей получили заботу и внимание',
    'statistics.baptisms': 'Крещений',
    'statistics.baptisms.hover': 'В прошлом году 12 человек приняли водное крещение. Следующее крещение состоится 9 мая 2026 года. Свяжитесь с пастором, если хотите подготовиться к крещению.',
    'statistics.baptisms.learnMore': 'Узнать о крещении',
    'statistics.sundaySchoolPeople': 'В воскресной школе',
    'statistics.sundaySchool.hover': 'Каждое воскресенье 80 детей изучают Библию в увлекательной форме. Занятия проходят во время служения для детей разных возрастов.',
    'statistics.sundaySchool.learnMore': 'Узнать о воскресной школе',
    'statistics.summerCamp': 'В летних лагерях',
    'statistics.summerCamp.hover': 'Каждое лето 90 детей и подростков участвуют в наших лагерях, где они познают Бога через игры, творчество и общение.',
    'statistics.summerCamp.learnMore': 'Узнать о летних лагерях',
    'statistics.childrenGifts': 'Детей получили подарки',
    'statistics.childrenGifts.hover': 'В рамках рождественской акции 800 детей из нуждающихся семей получили подарки и узнали о любви Божьей.',
    'statistics.familiesHelped': 'Семей получили помощь',
    'statistics.familiesHelped.hover': 'Через служение "Любовь и Забота" мы помогаем семьям в нужде продуктами, одеждой и практической поддержкой.',
    'statistics.childrenSchool': 'Детей подготовлено к школе',
    'statistics.childrenSchool.hover': 'Каждый год мы помогаем детям из нуждающихся семей подготовиться к школе, обеспечивая их необходимыми принадлежностями.',

    // Events
    'events.title': 'События',
    'events.subtitle': 'Будьте в курсе церковной жизни',
    'events.upcoming': 'Ближайшие события',
    'events.prayerMeeting': 'Молитва',
    'events.holyCommunion': 'Причастие',
    'events.sundayService': 'Воскресное служение',
    'events.news.title': 'Новости',
    'events.news.desc': 'Последние новости из жизни церкви',
    'events.news.content': 'Следите за нашими соцсетями для получения последних новостей.',
    'events.calendar.title': 'Календарь',
    'events.calendar.desc': 'Расписание богослужений',
    'events.calendar.content': 'Воскресенье 11:00, молитва по пятницам 18:00.',
    'events.training.title': 'Учебные мероприятия',
    'events.training.desc': 'Курс "Целостная Жизнь" 2026-2027',
    'events.training.content': 'Практический курс для духовного роста.',
    'events.training.link': 'Подробнее о курсе',
    'events.baptism.title': 'Водное крещение',
    'events.baptism.desc': 'Информация о крещении',
    'events.baptism.content': 'Крещение — важный шаг веры.',
    'events.baptism.nextDate': 'Следующее крещение: 9 мая 2026',
    'events.baptism.contactPastor': 'Свяжитесь с пастором, если хотите принять участие.',

    // Gallery
    'gallery.title': 'Галерея',
    'gallery.subtitle': 'Наша церковь и жизнь вокруг неё, прославляя Бога в каждом действии',
    'gallery.pageTitle': 'Галерея',
    'gallery.pageSubtitle': 'Наша церковь и жизнь вокруг неё, прославляя Бога в каждом действии',
    'gallery.followUs': 'Следите за нами в соцсетях',
    'gallery.viewAll': 'Смотреть всю галерею',
    
    // History extended
    'history.fetler.extended': 'Уже в нелегальной Латвии Фетлер смог проповедовать весть о спасении во всех возможных местах — на радио, в кинотеатрах, в городских парках, на речных пристанях, в тюрьмах, на кладбищах, на свадьбах.',
    'history.return.title': 'Возвращение на Родину',
    'history.return.text': 'Вильямс Фетлер вернулся в Латвию в 1923 году. Латвия стала независимым государством, и здесь царила свобода веры и проповеди. Поэтому весть о спасении в Иисусе Христе Фетлер мог проповедовать во всех возможных местах.',
    'history.temple.details': 'В Храме Спасения было несколько залов, из которых самый большой мог вместить более 2000 человек. Богослужения проходили на четырёх языках — латышском, русском, немецком и польском.',
    'history.interior.title': 'Служение в Храме',
    'history.interior.text': 'Богослужения длились от трёх до шести часов, но огонь Святого Духа был настолько ощутим, что время проходило незаметно. В башне Храма действовала молитвенная стража — 24 часа в сутки люди молились о пробуждении в Латвии.',
    'history.interior.caption': 'Большой зал Храма Спасения во время богослужения',
    'history.evangelization.label': 'Евангелизация',
    'history.legacy.title': 'Наследие Веры',
    'history.legacy.text': 'Сегодня Храм Спасения продолжает миссию, начатую почти 100 лет назад — прославлять Бога и взращивать учеников Христа. Мы храним богатое духовное наследие и с верой смотрим в будущее.',
    'history.resources.title': 'Исторические источники',
    'history.resources.fetlerArticle': 'Статья о Вильямсе Фетлере',
    'history.resources.lbcHistory': 'История ЛБЦ',
    'history.resources.encyclopedia': 'Энциклопедия: Баптисты в Латвии',
    'history.resources.lostLatvia': 'Утраченная Латвия: Храм Спасения',

    // Testimonies
    'testimonies.title': 'Свидетельства',
    'testimonies.subtitle': 'Истории изменённых жизней',
    'testimonies.viewAll': 'Читать все свидетельства',
    'testimonies.before': 'До',
    'testimonies.encounter': 'Встреча с Христом',
    'testimonies.after': 'После',
    'testimonies.share': 'Хотите поделиться своей историей?',
    'testimonies.shareButton': 'Связаться с нами',
    'testimonies.testimony1.name': 'Мария К.',
    'testimonies.testimony1.summary': 'Бог изменил мою жизнь, когда я пришла в эту церковь...',
    'testimonies.testimony1.before': 'Я жила в постоянной тревоге и не находила смысла в жизни.',
    'testimonies.testimony1.encounter': 'Друзья пригласили меня на служение, и я впервые почувствовала Божью любовь.',
    'testimonies.testimony1.after': 'Сегодня я живу с миром в сердце и служу в воскресной школе.',
    'testimonies.testimony2.name': 'Алексей П.',
    'testimonies.testimony2.summary': 'Из зависимости к свободе во Христе...',
    'testimonies.testimony2.before': 'Зависимость разрушала мою семью и карьеру.',
    'testimonies.testimony2.encounter': 'Пастор молился за меня, и я ощутил освобождение.',
    'testimonies.testimony2.after': 'Уже 5 лет я свободен и помогаю другим найти этот путь.',
    'testimonies.testimony3.name': 'Елена С.',
    'testimonies.testimony3.summary': 'Нашла настоящую семью в церкви...',
    'testimonies.testimony3.before': 'После развода я чувствовала себя одинокой.',
    'testimonies.testimony3.encounter': 'Домашняя группа приняла меня как семью.',
    'testimonies.testimony3.after': 'Теперь я веду женское служение и помогаю другим.',
    'testimonies.testimony4.name': 'Дмитрий В.',
    'testimonies.testimony4.summary': 'От атеизма к вере...',
    'testimonies.testimony4.before': 'Я был убеждённым атеистом.',
    'testimonies.testimony4.encounter': 'Изучение Библии открыло мне глаза на истину.',
    'testimonies.testimony4.after': 'Сегодня я учитель воскресной школы.',
    'testimonies.testimony5.name': 'Анна Л.',
    'testimonies.testimony5.summary': 'Исцеление от прошлых ран...',
    'testimonies.testimony5.before': 'Детские травмы не давали мне жить полноценно.',
    'testimonies.testimony5.encounter': 'Через душепопечение я нашла исцеление.',
    'testimonies.testimony5.after': 'Бог восстановил мои отношения с семьёй.',

    // Ministries
    'ministries.title': 'Служения',
    'ministries.subtitle': 'Найдите своё место в нашей общине',
    'ministries.wantToServe': 'Хочу служить',
    'ministries.leader': 'Лидер',
    'ministries.worship.title': 'Богослужения',
    'ministries.worship.desc': 'Еженедельные богослужения и прославление',
    'ministries.worship.hoverInfo': 'Каждое воскресенье в 11:00 мы собираемся для совместного прославления Бога. Служение включает пение гимнов, молитву, проповедь Слова Божьего и общение. Мы служим на русском и латышском языках, чтобы каждый мог участвовать в полной мере.',
    'ministries.sundaySchool.title': 'Воскресная школа',
    'ministries.sundaySchool.desc': 'Библейское обучение для детей',
    'ministries.sundaySchool.hoverInfo': 'Каждое воскресенье во время служения дети изучают Библию в увлекательной и доступной форме. Занятия включают истории, игры, творчество и песни. Мы верим, что духовное воспитание начинается с детства.',
    'ministries.ribaClub.title': 'Клуб Рыба',
    'ministries.ribaClub.desc': 'Подростковый клуб (12-16 лет)',
    'ministries.ribaClub.hoverInfo': 'Клуб Рыба — это место, где подростки могут безопасно общаться, задавать вопросы о вере и жизни. Мы организуем игры, обсуждения, походы и лагеря. Наша цель — помочь подросткам найти свой путь к Богу.',
    'ministries.youth.title': 'Молодёжь',
    'ministries.youth.desc': 'Служение для молодых людей',
    'ministries.youth.hoverInfo': 'Молодёжное служение объединяет молодых людей для изучения Библии, общения и служения. Мы проводим еженедельные встречи, молодёжные вечера, поездки и социальные проекты. Присоединяйся к нам!',
    'ministries.youngLife.title': 'YoungLife',
    'ministries.youngLife.desc': 'Программа для подростков',
    'ministries.youngLife.hoverInfo': 'YoungLife — международная программа для подростков, которая помогает им познакомиться с Иисусом через дружбу и веселье. Мы встречаемся еженедельно, проводим лагеря и мероприятия.',
    'ministries.loveAndCare.title': 'Любовь и Забота',
    'ministries.loveAndCare.desc': 'Практическая помощь и забота о нуждающихся детях',
    'ministries.loveAndCare.hoverInfo': 'Служение "Любовь и Забота" оказывает практическую помощь нуждающимся семьям и детям. Мы собираем продукты, одежду, школьные принадлежности и организуем поддержку для тех, кто переживает трудные времена.',
    'ministries.choir.title': 'Хор',
    'ministries.choir.desc': 'Музыкальное служение',
    'ministries.choir.hoverInfo': 'Наш хор служит прославлением Бога через музыку. Мы поём на богослужениях, праздниках и особых мероприятиях. Репетиции проходят еженедельно. Приглашаем всех, кто любит петь!',
    'ministries.smallGroups.title': 'Домашние группы',
    'ministries.smallGroups.desc': 'Малые группы для общения',
    'ministries.smallGroups.hoverInfo': 'Домашние группы — это малые общины, которые собираются в домах для изучения Библии, молитвы и общения. Это место, где можно найти настоящих друзей и поддержку. Группы встречаются в разных районах Риги.',
    'ministries.mensMinistry.title': 'Мужское служение',
    'ministries.mensMinistry.desc': 'Братство и рост для мужчин',
    'ministries.mensMinistry.hoverInfo': 'Мужское служение помогает мужчинам расти духовно, укреплять семьи и строить настоящее братство. Мы проводим встречи, походы, спортивные мероприятия и совместное изучение Библии.',
    'ministries.womensMinistry.title': 'Женское служение',
    'ministries.womensMinistry.desc': 'Общение и поддержка для женщин',
    'ministries.womensMinistry.hoverInfo': 'Женское служение создаёт пространство для общения, молитвы и взаимной поддержки. Мы проводим встречи, чаепития, изучение Библии и мероприятия для женщин всех возрастов.',
    'ministries.media.title': 'Медиа команда',
    'ministries.media.desc': 'Техническое и медиа служение',
    'ministries.media.hoverInfo': 'Медиа команда обеспечивает качественное звуковое и визуальное сопровождение служений. Мы занимаемся съёмкой, монтажом, онлайн-трансляциями и управлением социальными сетями церкви.',
    'ministries.counselling.title': 'Душепопечение',
    'ministries.counselling.desc': 'Исцеление сердец',
    'ministries.counselling.hoverInfo': 'Служение душепопечения помогает людям обрести внутреннее исцеление через молитву, разговор и библейское наставление. Мы сопровождаем людей в трудные моменты жизни, помогая найти мир и восстановление во Христе.',

    // Contacts
    'contacts.title': 'Контакты',
    'contacts.pastor': 'Пастор',
    'contacts.manager': 'Управляющий',
    'contacts.address': 'Адрес',
    'contacts.serviceTimes': 'Время служений',
    'contacts.parking': 'Парковка',
    'contacts.parkingAvailable': 'Парковка доступна на территории церкви',
    'contacts.prayerFriday': 'Молитва: Пятница 18:00',
    'contacts.socialMedia': 'Социальные сети',

    // Donations
    'donations.title': 'Пожертвования',
    'donations.subtitle': 'Ваши пожертвования помогают нам служить',
    'donations.whyGive': 'Почему жертвовать?',
    'donations.whyGiveText': 'Ваши пожертвования поддерживают служение церкви, помогают нуждающимся и распространяют Евангелие.',
    'donations.bankDetails': 'Банковские реквизиты',
    'donations.recipient': 'Получатель',
    'donations.bank': 'Банк',
    'donations.thankYou': 'Благодарим за вашу щедрость!',
    'donations.footer': 'Поддержите служение церкви',
    'donations.projects.title': 'Церковные проекты',
    'donations.projects.building.title': 'Здание церкви',
    'donations.projects.building.desc': 'Содержание и ремонт',
    'donations.projects.sundaySchool.title': 'Воскресная школа',
    'donations.projects.sundaySchool.desc': 'Материалы и программы',
    'donations.projects.summerCamp.title': 'Летние лагеря',
    'donations.projects.summerCamp.desc': 'Отдых для детей',
    'donations.projects.charity.title': 'Благотворительность',
    'donations.projects.charity.desc': 'Помощь нуждающимся',
    'donations.projects.families.title': 'Помощь семьям',
    'donations.projects.families.desc': 'Поддержка семей',
    'donations.cta': 'Пожертвовать',
    'donations.impact': 'Как используются пожертвования',
    'donations.impactBuilding': 'Содержание здания церкви',
    'donations.impactMinistries': 'Поддержка служений',
    'donations.impactCharity': 'Благотворительность',

    // Footer
    'footer.rights': 'Все права защищены.',
    'footer.aboutText': 'Место, где люди духовно крепнут и учатся распространению Евангелия.',
    'footer.navigation': 'Навигация',
    'footer.resources': 'Ресурсы',
    'footer.scanQR': 'Сканируйте для регистрации',
    
    // ===== TRAINING PROGRAM TRANSLATIONS =====
    // Hero
    'hero.year': '2026-2027',
    'hero.dates': '19.09 — 22.05',
    'hero.time': '10:00 — 14:00',
    'hero.age': '18 - 50 ЛЕТ',
    'hero.rhythm': '1 СУББОТА В МЕСЯЦ',
    'hero.title': 'ЦЕЛОСТНАЯ ЖИЗНЬ',
    'hero.subtitle': 'Практический курс для тех, кто хочет построить прочный фундамент в эпоху перемен, основанный на библейских принципах и практическом фундаменте.',
    'hero.cta': 'Регистрация Открыта',
    
    // Philosophy
    'philosophy.title': 'Цель и Философия Курса',
    'philosophy.text': 'Обучить лидеров и церковь библейским истинам для обретения внутреннего мира и баланса в важнейших сферах жизни, а также соединить с Богом для обретения Шалома. Каждый человек призван найти свою полноценную жизнь и пребывать в мире. Результат — это четкий план действий, как реализовать себя в каждой важной сфере жизни в соответствии с Божьим замыслом.',
    
    // Benefits
    'benefits.title': 'Что это вам даст?',
    'benefits.clarity.title': 'Ясность Призвания',
    'benefits.clarity.text': 'Перестань жить по инерции. Определи свою миссию и пойми, куда Бог зовет тебя в этом сезоне.',
    'benefits.core.title': 'Внутренний Стержень',
    'benefits.core.text': 'Развей устойчивость к стрессу, выгоранию и тревоге, опираясь на вечные истины.',
    'benefits.wisdom.title': 'Практическая Мудрость',
    'benefits.wisdom.text': 'Получи работающие инструменты: простые, но мощные вещи, которые могут изменить твою жизнь к лучшему.',
    'benefits.connections.title': 'Глубокие Связи',
    'benefits.connections.text': 'Найди друзей и наставников, с которыми можно быть настоящим и расти вместе.',
    
    // Target
    'target.title': 'Для Кого Это?',
    'target.text': 'Этот курс для лидеров, активных прихожан и всех, кто стремится к осознанной жизни и хочет обрести баланс (18-50 лет).',
    'target.checklist.title': 'Это для тебя, если:',
    'target.persona.1': 'У меня есть видение, но я не знаю, как его достичь',
    'target.persona.2': 'Я ставлю одни и те же цели, но терплю неудачу',
    'target.persona.3': 'Я знаю, чего хочу и как это сделать, но мне нужна поддержка',
    'target.persona.4': 'Я разный человек в церкви, на работе и дома',
    'target.persona.5': 'Я вроде бы успешен, но не знаю, ради чего',
    'target.persona.6': 'Я успешен в карьере, но разбит дома (или счастлив дома, но испытываю финансовые трудности)',
    'target.persona.7': 'У меня не расставлены приоритеты или я борюсь с одним из аспектов колеса баланса',
    'target.persona.8': 'Я не хочу расти, но внутренний голос / Бог говорит, что мне нужно измениться, и я откладываю это, я не в мире',
    
    // Method
    'method.title': 'Как мы учимся',
    'method.subtitle': 'Мы используем метод Impact Based Learning (Обучение, основанное на влиянии). Минимум лекций, но больше работы над рефлексией, практикой, обсуждениями и формированием привычек.',
    'method.theory.title': 'Короткая Теория',
    'method.theory.text': 'Библейская истина + Мировые теоретические знания, адаптированные для нашего контекста.',
    'method.apply.title': 'Применение теории',
    'method.apply.text': 'Ты уходишь с заполненным планом, а не просто идеей.',
    'method.groups.title': 'Малые Группы',
    'method.groups.text': 'Честная обратная связь, молитва и обсуждение кейсов в безопасной среде.',
    'method.mentor.title': 'Менторинг и Практика',
    'method.mentor.text': 'Задания между модулями для внедрения навыков в реальную жизнь (семья, работа).',
    
    // Approach
    'approach.title': 'Наш Подход',
    'approach.1.title': 'Осознанность',
    'approach.1.text': 'Как Бог видит это? Чего Он хочет для этой сферы?',
    'approach.2.title': 'Цель',
    'approach.2.text': 'Где вы хотите быть и каков разрыв между текущим и желаемым?',
    'approach.3.title': 'Навыки',
    'approach.3.text': 'Инструменты: Библейская мудрость и практические методы.',
    'approach.4.title': 'План Действий',
    'approach.4.text': 'Какие конкретные шаги вы предпримете?',
    'approach.5.title': 'Закрепление',
    'approach.5.text': 'Поддержка среды и привычек для долгосрочных изменений.',
    
    // Wheel
    'wheel.title': 'Библейский Баланс',
    'wheel.subtitle': 'Мы не делим жизнь на "духовное" и "светское". Наведите на сферу, чтобы увидеть её смысл в Божьем замысле.',
    'wheel.hover': 'Наведите курсор на кнопку выше, чтобы раскрыть значение.',
    'wheel.purpose': 'Предназначение',
    'wheel.people': 'Люди',
    'wheel.body': 'Тело',
    'wheel.mind': 'Разум',
    'wheel.finance': 'Финансы',
    'wheel.character': 'Характер',
    'wheel.church': 'Церковь',
    'wheel.piety': 'Благочестие',
    'wheel.shalom': 'ШАЛОМ',
    'wheel.purpose.desc': 'Ваше уникальное призвание и миссия в этом мире.',
    'wheel.people.desc': 'Отношения, семья и сообщество вокруг вас.',
    'wheel.body.desc': 'Физическое здоровье — ваше тело как храм Духа.',
    'wheel.mind.desc': 'Обновление ума, мышление и личностный рост.',
    'wheel.finance.desc': 'Управление ресурсами как добрый управитель.',
    'wheel.character.desc': 'Плод Духа и формирование привычек.',
    'wheel.church.desc': 'Ваше место в Теле Христа и служение.',
    'wheel.piety.desc': 'Близость с Богом, молитва и духовные практики.',
    'wheel.purpose.quote': '«Ибо мы — Его творение, созданы во Христе Иисусе на добрые дела» — Еф. 2:10',
    'wheel.people.quote': '«Возлюби ближнего твоего, как самого себя» — Мф. 22:39',
    'wheel.body.quote': '«Тело ваше есть храм живущего в вас Святого Духа» — 1 Кор. 6:19',
    'wheel.mind.quote': '«Преобразуйтесь обновлением ума вашего» — Рим. 12:2',
    'wheel.finance.quote': '«Верный в малом и во многом верен» — Лк. 16:10',
    'wheel.character.quote': '«Плод же духа: любовь, радость, мир, долготерпение...» — Гал. 5:22',
    'wheel.church.quote': '«Вы — тело Христово, а порознь — члены» — 1 Кор. 12:27',
    'wheel.piety.quote': '«Приблизьтесь к Богу, и приблизится к вам» — Иак. 4:8',
    
    // Calendar
    'calendar.title': 'Календарь Сессий',
    'calendar.subtitle': 'Даты проведения курса с сентября 2026 по июнь 2027',
    'calendar.break': 'Зимний перерыв',
    
    // Sessions
    'sessions.title': 'Программа Сессий',
    'sessions.about': 'О СЕССИИ',
    'sessions.tools': 'ИНСТРУМЕНТЫ',
    'sessions.break': 'Зимний Перерыв (Декабрь - Январь)',
    
    'session.1.month': 'СЕНТЯБРЬ',
    'session.1.date': '19 СЕН',
    'session.1.title': '1. Предназначение',
    'session.1.about': 'Старт программы. Мы проведем глубокий аудит вашей жизни и определим разрыв между тем, где вы есть, и где Бог хочет вас видеть.',
    'session.1.tools': 'Колесо Баланса (Библейская версия)\nФреймворк Икигай для поиска призвания\nНаписание "Письма из Будущего"',
    
    'session.2.month': 'ОКТЯБРЬ',
    'session.2.date': '17 ОКТ',
    'session.2.title': '2. Люди и Отношения',
    'session.2.about': 'Мы научимся говорить о сложных вещах без агрессии и устанавливать границы, которые сохраняют любовь и уважение.',
    'session.2.tools': 'Ненасильственное Общение (ННО)\nАудит Отношений\nСкрипты для установки границ',
    
    'session.3.month': 'НОЯБРЬ',
    'session.3.date': '21 НОЯ',
    'session.3.title': '3. Тело и Здоровье',
    'session.3.about': 'Ваше тело — Храм. Мы разберем физиологию энергии, сна и питания.',
    'session.3.tools': 'Протокол гигиены сна\nСоздание "Меню Радостного Движения"\nАнализ энергетических пиков дня',
    
    'session.4.month': 'ДЕКАБРЬ',
    'session.4.date': '12 ДЕК',
    'session.4.title': '4. Личностный Рост и Карьера',
    'session.4.about': 'Работа с мышлением. Как наши убеждения саботируют нас? Мы научимся "обновлять ум" (Рим 12:2).',
    'session.4.tools': 'Техника "Fear Setting" (Тим Феррис)\nКогнитивный рефрейминг убеждений',
    
    'session.5.month': 'ЯНВАРЬ',
    'session.5.date': '30 ЯНВ',
    'session.5.title': '5. Характер и Привычки',
    'session.5.about': 'Характер — это сумма ваших привычек. Мы внедрим науку формирования привычек.',
    'session.5.tools': 'Петля Привычки (Atomic Habits)\nHabit Stacking\nSMART-цели',
    
    'session.6.month': 'ФЕВРАЛЬ',
    'session.6.date': '20 ФЕВ',
    'session.6.title': '6. Финансы и Управление',
    'session.6.about': 'Мы перейдем от стресса выживания к радости управления ресурсами Царства.',
    'session.6.tools': 'Аудит "черных дыр" бюджета\nМетод конвертов (цифровой)\nПлан щедрости',
    
    'session.7.month': 'МАРТ',
    'session.7.date': '20 МАР',
    'session.7.title': '7. Церковь',
    'session.7.about': 'Как найти свое место в Теле Христа и превратить свой дом в место служения?',
    'session.7.tools': 'Тест духовных даров\nПрактика гостеприимства',
    
    'session.8.month': 'АПРЕЛЬ',
    'session.8.date': '24 АПР',
    'session.8.title': '8. Благочестие и Шалом',
    'session.8.about': 'Искусство замедляться и слышать Бога в шумном мире.',
    'session.8.tools': 'Lectio Divina (Молитвенное чтение)\nПрактика Шаббата\nReview года',
    
    'session.9.month': 'МАЙ',
    'session.9.date': '22 МАЯ',
    'session.9.title': '9. Разум и Эмоции',
    'session.9.about': 'Работа с эмоциональным интеллектом и внутренней гармонией.',
    'session.9.tools': 'Эмоциональный аудит\nТехники осознанности\nПланирование на год',
    
    'session.10.month': 'ИЮНЬ 2027',
    'session.10.date': '12 ИЮН',
    'session.10.title': 'ФИНАЛ: Рефлексия и Вечер Лидеров',
    'session.10.about': 'Финальная сессия. Время глубокой рефлексии пройденного пути, закрепления полезных привычек и празднования побед вместе с Вечером Лидеров.',
    'session.10.tools': 'Годовой обзор (Year Compass)\nЗакрепление ключевых привычек\nПраздничный ужин с лидерами',
    
    // Organization
    'org.title': 'Организация и Тайминг',
    'org.location': 'Локация',
    'org.location.value': 'Зал Рыба\nLāčplēša 117, Riga\n2 этаж.',
    'org.cost': 'Стоимость',
    'org.cost.value': 'Покрывается церковью «Храм Спасения»\n+ 10 EUR за сессию (кофе и закуски)',
    'org.commitment': 'Посвящение',
    'org.commitment.value': 'Мы ожидаем участия в каждой сессии.',
    'org.details': 'Детали',
    'org.details.value': 'Возраст: 18 - 50 лет\nДаты: 19.09.2026 — 12.06.2027\nРитм: 1 Суббота в месяц',
    
    // Schedule
    'schedule.title': 'Расписание Субботы',
    'schedule.welcome': 'Приветствие',
    'schedule.welcome.desc': 'Чек-ин: «Одно слово, описывающее неделю». Кофе.',
    'schedule.part1': 'Часть 1: Осознанность',
    'schedule.part1.desc': 'Взгляд Бога: Чтение Якоря Писания.\n«Где вы сейчас по шкале 1-10?» Определение разрыва.',
    'schedule.part2': 'Часть 2: Навыки',
    'schedule.part2.desc': 'Теория и Демо: Ключевой инструмент, пропущенный через библейскую призму.',
    'schedule.coffee': 'Кофе-брейк',
    'schedule.coffee.desc': 'Неструктурированное время для общения.',
    'schedule.part3': 'Часть 3: Практикум',
    'schedule.part3.desc': 'Глубокое погружение в теорию и практический смысл вместе с обсуждением в группах.',
    'schedule.part4': 'Часть 4: Закрепление',
    'schedule.part4.desc': 'Ручка и Бумага: Заполнение рабочих листов. Работа в малых группах (2-3 чел).',
    'schedule.checkout': 'Чек-аут',
    'schedule.checkout.desc': 'Домашнее задание на месяц. «Твой один следующий шаг?»',
    
    // Team
    'team.title': 'Команда',
    'team.elya.name': 'Эля Файзулина',
    'team.elya.role': 'ТЕЛО И ЗДОРОВЬЕ',
    'team.elya.desc': 'Научит относиться к телу как к храму: энергия, сон и здоровое движение.',
    'team.alex.name': 'Александр Звирид',
    'team.alex.role': 'ЦЕРКОВЬ И ОБЩЕСТВО',
    'team.alex.desc': 'Раскроет тему служения, лидерства и создания благочестивой среды вокруг себя.',
    'team.tanya.name': 'Таня Абрамова',
    'team.tanya.role': 'ОТНОШЕНИЯ И ДУХ',
    'team.tanya.desc': 'С глубоким духовным практикам пребывания в Боге.',
    'team.sasha.name': 'Саша Абрамов',
    'team.sasha.role': 'ПРЕДНАЗНАЧЕНИЕ',
    'team.sasha.desc': 'Проведет вас через процесс поиска личной миссии и стратегического видения жизни.',
    'team.richards.name': 'Рихардс Гаранчс',
    'team.richards.role': 'ФИНАНСЫ И ХАРАКТЕР',
    'team.richards.desc': 'Поможет навести порядок в бюджете и построить "атомные привычки" для долгосрочного роста.',
    'team.victoria.name': 'Виктория Гаранча',
    'team.victoria.role': 'РАЗУМ И КАРЬЕРА',
    'team.victoria.desc': 'Научит преодолевать страхи и ограничивающие убеждения.',
  },
  en: {
    // Church Info
    'church.name': 'Salvation Temple',
    'church.officialName': 'Riga Missionary Baptist Church',
    'church.shortName': 'Evangelical Church',
    'church.tagline': 'Evangelical Church in Riga',
    'church.welcome': 'Welcome to our home! We are a living community of believers united by love for Christ.',
    'church.heroWelcome': 'Experience God\'s presence at church this Sunday.',
    'church.shortDesc': 'Evangelical Christian church serving Riga with love and faith.',
    'church.serviceSunday': 'Sunday 11:00',
    'church.serviceWednesday': 'Wednesday 18:00',
    'church.serviceLanguages': 'Russian and Latvian',
    'church.planVisit': 'Plan a Visit',
    'church.watchLive': 'Watch Live',

    // Hero
    'hero.comeAndSee': 'Come and See',
    'hero.changed': 'Changed',
    'hero.word.hearts': 'Hearts',
    'hero.word.lives': 'Lives',
    'hero.word.relationships': 'Relationships',
    'hero.word.minds': 'Minds',
    'hero.word.personality': 'Personality',
    'hero.word.values': 'Values',
    'hero.word.eternities': 'Eternities',
    'hero.changing.hearts': 'Changed Hearts',
    'hero.changing.lives': 'Changed Lives',
    'hero.changing.relationships': 'Changed Relationships',
    'hero.changing.minds': 'Changed Minds',
    'hero.changing.personality': 'Changed Personality',
    'hero.changing.values': 'Changed Values',
    'hero.changing.eternities': 'Changed Eternities',

    // Navigation
    'nav.about': 'About',
    'nav.history': 'History',
    'nav.events': 'Events',
    'nav.ministries': 'Ministries',
    'nav.testimonies': 'Testimonies',
    'nav.contacts': 'Contacts',
    'nav.donations': 'Donations',
    'nav.program': 'Program',
    'nav.calendar': 'Calendar',
    'nav.team': 'Team',
    'nav.register': 'Register',

    // About
    'about.title': 'About Us',
    'about.subtitle': 'Get to know our church',
    'about.intro': 'Salvation Temple — a place where people grow spiritually and learn to spread the Gospel.',
    'about.getToKnowUs': 'Get to Know Us',
    'about.vision.title': 'Our Vision',
    'about.vision.text': 'Salvation Temple glorifies God by creating and nurturing disciples fully instructed in Christ in the Latgale region of Riga, who in turn create new disciples, leading to planting a new church in Latvia.',
    'about.vision.textShort': 'Salvation Temple glorifies God by creating and nurturing disciples fully instructed in Christ in the Latgale region of Riga, who in turn create new disciples, leading to planting a new church in Latvia.',
    'about.values.title': 'Our Values',
    'about.values.christ.title': 'Christ is our center',
    'about.values.christ.paragraph': 'Christ is our center and focus in everything we do. We remember who He was and what He did, as well as what He does now through the Holy Spirit.',
    'about.values.bible.title': 'Bible is our truth',
    'about.values.bible.paragraph': 'God\'s Word is the foundation of our faith. The Gospel and all books of the Bible guide our life and ministry.',
    'about.values.discipleship.title': 'Discipleship',
    'about.values.discipleship.paragraph': 'We grow through mentoring and fellowship for spiritual growth, helping each other become mature followers of Christ.',
    'about.values.mission.title': 'Mission',
    'about.values.mission.paragraph': 'We share the good news in word and deed, demonstrating God\'s love through practical service to those around us.',
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'Salvation Temple — a place where people grow spiritually and learn to spread the Gospel.',
    'about.historyButton': 'Learn our history',

    // Statistics
    'statistics.title': 'Our Community',
    'statistics.subtitle': 'We are a family of believers of different ages',
    'statistics.total': 'Total members',
    'statistics.members.hover': 'We are a diverse community of 150 people of all ages and walks of life. Children, youth, families, and seniors together praise God.',
    'statistics.pastYear.title': 'Our church in the past year in numbers',
    'statistics.history.title': 'Throughout church history',
    'statistics.history.baptisms': 'Baptisms',
    'statistics.history.sundaySchool': 'Children in Sunday School',
    'statistics.history.summerCamps': 'Summer camp participants',
    'statistics.history.families': 'Families helped',
    'statistics.history.childrenCare': 'Children received care and attention',
    'statistics.baptisms': 'Baptisms',
    'statistics.baptisms.hover': 'Last year 12 people were baptized. The next baptism will be on May 9, 2026. Contact the pastor if you want to prepare for baptism.',
    'statistics.baptisms.learnMore': 'Learn about baptism',
    'statistics.sundaySchoolPeople': 'In Sunday School',
    'statistics.sundaySchool.hover': 'Every Sunday 80 children study the Bible in an engaging way. Classes are held during the service for children of different ages.',
    'statistics.sundaySchool.learnMore': 'Learn about Sunday School',
    'statistics.summerCamp': 'In summer camps',
    'statistics.summerCamp.hover': 'Each summer 90 children and teenagers participate in our camps, where they experience God through games, creativity, and fellowship.',
    'statistics.summerCamp.learnMore': 'Learn about summer camps',
    'statistics.childrenGifts': 'Children received gifts',
    'statistics.childrenGifts.hover': 'As part of the Christmas campaign, 800 children from needy families received gifts and learned about God\'s love.',
    'statistics.familiesHelped': 'Families helped in need',
    'statistics.familiesHelped.hover': 'Through the Love & Care ministry we help families in need with food, clothing, and practical support.',
    'statistics.childrenSchool': 'Children prepared for school',
    'statistics.childrenSchool.hover': 'Every year we help children from needy families prepare for school by providing them with necessary supplies.',

    // Events
    'events.upcoming': 'Upcoming Events',
    'events.prayerMeeting': 'Prayer',
    'events.holyCommunion': 'Communion',
    'events.sundayService': 'Sunday Service',
    'events.baptism.nextDate': 'Next baptism: May 9, 2026',
    'events.baptism.contactPastor': 'Contact the pastor if you wish to participate.',

    // Gallery
    'gallery.title': 'Gallery',
    'gallery.subtitle': 'Our church and life around it, praising God in every action',
    'gallery.viewAll': 'View full gallery',
    'gallery.pageTitle': 'Gallery',
    'gallery.pageSubtitle': 'Our church and life around it, praising God in every action',
    
    // History extended (English)
    'history.fetler.extended': 'In newly independent Latvia, Fetler could preach the message of salvation everywhere — on radio, in cinemas, city parks, river piers, prisons, cemeteries, and weddings.',
    'history.return.title': 'Return to Homeland',
    'history.return.text': 'Viljams Fetlers returned to Latvia in 1923. Latvia had become an independent state with freedom of faith and preaching. Therefore, the message of salvation in Jesus Christ could be proclaimed everywhere.',
    'history.temple.details': 'Salvation Temple had several halls, the largest of which could accommodate more than 2000 people. Services were held in four languages — Latvian, Russian, German, and Polish.',
    'history.interior.title': 'Ministry in the Temple',
    'history.interior.text': 'Services lasted three to six hours, but the fire of the Holy Spirit was so palpable that time flew by. In the tower of the Temple, a prayer watch operated — 24 hours a day people prayed for revival in Latvia.',
    'history.interior.caption': 'The Great Hall of Salvation Temple during a service',
    'history.evangelization.label': 'Evangelization',
    'history.legacy.title': 'Legacy of Faith',
    'history.legacy.text': 'Today, Salvation Temple continues the mission begun almost 100 years ago — to glorify God and nurture disciples of Christ. We preserve a rich spiritual heritage and look to the future with faith.',
    'history.resources.title': 'Historical Resources',
    'history.resources.fetlerArticle': 'Article about Viljams Fetlers',
    'history.resources.lbcHistory': 'LBC History',
    'history.resources.encyclopedia': 'Encyclopedia: Baptists in Latvia',
    'history.resources.lostLatvia': 'Lost Latvia: Salvation Temple',

    // Testimonies
    'testimonies.title': 'Testimonies',
    'testimonies.subtitle': 'Stories of changed lives',
    'testimonies.viewAll': 'Read all testimonies',
    'testimonies.before': 'Before',
    'testimonies.encounter': 'Encounter with Christ',
    'testimonies.after': 'After',
    'testimonies.share': 'Want to share your story?',
    'testimonies.shareButton': 'Contact us',
    'testimonies.testimony1.name': 'Maria K.',
    'testimonies.testimony1.summary': 'God changed my life when I came to this church...',
    'testimonies.testimony1.before': 'I lived in constant anxiety and found no meaning in life.',
    'testimonies.testimony1.encounter': 'Friends invited me to a service, and I felt God\'s love for the first time.',
    'testimonies.testimony1.after': 'Today I live with peace in my heart and serve in Sunday school.',
    'testimonies.testimony2.name': 'Alexey P.',
    'testimonies.testimony2.summary': 'From addiction to freedom in Christ...',
    'testimonies.testimony2.before': 'Addiction was destroying my family and career.',
    'testimonies.testimony2.encounter': 'The pastor prayed for me, and I experienced freedom.',
    'testimonies.testimony2.after': 'For 5 years I\'ve been free and help others find this path.',
    'testimonies.testimony3.name': 'Elena S.',
    'testimonies.testimony3.summary': 'Found a true family in church...',
    'testimonies.testimony3.before': 'After divorce, I felt lonely.',
    'testimonies.testimony3.encounter': 'A home group accepted me as family.',
    'testimonies.testimony3.after': 'Now I lead women\'s ministry and help others.',

    // Contacts
    'contacts.prayerFriday': 'Prayer: Friday 18:00',

    // Donations
    'donations.whyGive': 'Why Give?',
    'donations.whyGiveText': 'Your donations support church ministry, help those in need, and spread the Gospel.',
    'donations.impact': 'How donations are used',
    'donations.impactBuilding': 'Church building maintenance',
    'donations.impactMinistries': 'Ministry support',
    'donations.impactCharity': 'Charity work',
    'donations.projects.title': 'Church Projects',
    'donations.projects.building.title': 'Church Building',
    'donations.projects.building.desc': 'Maintenance & repairs',
    'donations.projects.sundaySchool.title': 'Sunday School',
    'donations.projects.sundaySchool.desc': 'Materials & programs',
    'donations.projects.summerCamp.title': 'Summer Camps',
    'donations.projects.summerCamp.desc': 'Activities for children',
    'donations.projects.charity.title': 'Charity',
    'donations.projects.charity.desc': 'Helping those in need',
    'donations.projects.families.title': 'Family Support',
    'donations.projects.families.desc': 'Supporting families',

    // Footer
    'footer.aboutText': 'A place where people grow spiritually and learn to spread the Gospel.',
    'footer.navigation': 'Navigation',
    'footer.resources': 'Resources',

    // Events Section
    'events.title': 'Events',
    'events.subtitle': 'Stay up to date with church life and upcoming events',
    'events.news.title': 'News',
    'events.news.desc': 'Latest news and updates from church life',
    'events.news.content': 'Follow our social media for the latest news and updates.',
    'events.calendar.title': 'Calendar',
    'events.calendar.desc': 'Schedule of services and events',
    'events.calendar.content': 'Sunday service at 11:00, Bible studies on Wednesdays at 18:00.',
    'events.training.title': 'Training Events',
    'events.training.desc': '"Wholesome Life" Course 2026-2027',
    'events.training.content': 'A practical course for those who want to build a solid foundation based on biblical principles.',
    'events.training.link': 'Learn more about the course',
    'events.baptism.title': 'Water Baptism',
    'events.baptism.desc': 'Information about baptism and preparation',
    'events.baptism.content': 'Baptism is an important step of faith. Contact us for information about baptism preparation.',

    // Ministries Section
    'ministries.title': 'Ministries',
    'ministries.subtitle': 'Find your place in our community and serve with us',
    'ministries.wantToServe': 'I Want to Serve',
    'ministries.leader': 'Leader',
    'ministries.worship.title': 'Worship Services',
    'ministries.worship.desc': 'Weekly services and praise',
    'ministries.worship.hoverInfo': 'Every Sunday at 11:00 we gather for worship. The service includes hymns, prayer, preaching of the Word, and fellowship. We serve in Russian and Latvian so everyone can participate fully.',
    'ministries.sundaySchool.title': 'Sunday School',
    'ministries.sundaySchool.desc': 'Bible education for children',
    'ministries.sundaySchool.hoverInfo': 'Every Sunday during the service, children study the Bible in an engaging way. Classes include stories, games, crafts, and songs. We believe spiritual education begins in childhood.',
    'ministries.ribaClub.title': 'Riba Club',
    'ministries.ribaClub.desc': 'Teen club (12-16 years)',
    'ministries.ribaClub.hoverInfo': 'Riba Club is a safe space for teens to connect, ask questions about faith and life. We organize games, discussions, trips, and camps. Our goal is to help teens find their path to God.',
    'ministries.youth.title': 'Youth Ministry',
    'ministries.youth.desc': 'Ministry for young people',
    'ministries.youth.hoverInfo': 'Youth ministry brings young people together for Bible study, fellowship, and service. We hold weekly meetings, youth nights, trips, and social projects. Join us!',
    'ministries.youngLife.title': 'YoungLife',
    'ministries.youngLife.desc': 'Program for teenagers',
    'ministries.youngLife.hoverInfo': 'YoungLife is an international program helping teens meet Jesus through friendship and fun. We meet weekly, run camps and events.',
    'ministries.loveAndCare.title': 'Love & Care',
    'ministries.loveAndCare.desc': 'Practical help and care for children in need',
    'ministries.loveAndCare.hoverInfo': 'Love & Care provides practical help to families and children in need. We collect food, clothing, school supplies and organize support for those going through difficult times.',
    'ministries.choir.title': 'Choir',
    'ministries.choir.desc': 'Music ministry',
    'ministries.choir.hoverInfo': 'Our choir serves through praising God with music. We sing at services, holidays, and special events. Rehearsals are weekly. All who love to sing are welcome!',
    'ministries.smallGroups.title': 'Home Groups',
    'ministries.smallGroups.desc': 'Small groups for fellowship',
    'ministries.smallGroups.hoverInfo': 'Home groups are small communities that gather in homes for Bible study, prayer, and fellowship. A place to find true friends and support. Groups meet in different areas of Riga.',
    'ministries.mensMinistry.title': "Men's Ministry",
    'ministries.mensMinistry.desc': 'Brotherhood and growth for men',
    'ministries.mensMinistry.hoverInfo': "Men's ministry helps men grow spiritually, strengthen families, and build true brotherhood. We hold meetings, trips, sports events, and joint Bible study.",
    'ministries.womensMinistry.title': "Women's Ministry",
    'ministries.womensMinistry.desc': 'Fellowship and support for women',
    'ministries.womensMinistry.hoverInfo': "Women's ministry creates space for fellowship, prayer, and mutual support. We hold meetings, tea gatherings, Bible studies, and events for women of all ages.",
    'ministries.media.title': 'Media Team',
    'ministries.media.desc': 'Technical and media ministry',
    'ministries.media.hoverInfo': 'The media team ensures quality audio and visual support for services. We handle filming, editing, live streaming, and managing the church social media.',
    'ministries.counselling.title': 'Counselling',
    'ministries.counselling.desc': 'Healing hearts',
    'ministries.counselling.hoverInfo': 'The counselling ministry helps people find inner healing through prayer, conversation, and biblical guidance. We accompany people in difficult moments, helping them find peace and restoration in Christ.',
    'ministries.serve.title': 'Want to Serve',
    'ministries.serve.desc': 'Find your ministry',

    // Care Section
    'care.title': 'Care & Support',
    'care.subtitle': 'We are here to support you in any life situation',
    'care.prayer.title': 'Prayer Support',
    'care.prayer.desc': 'Send us your prayer request and we will pray together with you.',
    'care.prayer.cta': 'Submit Request',
    'care.counseling.title': 'Pastoral Counseling',
    'care.counseling.desc': 'Pastoral counseling for those who need spiritual support and guidance.',
    'care.counseling.cta': 'Schedule',

    // Contacts Section
    'contacts.title': 'Contacts',
    'contacts.pastor': 'Pastor',
    'contacts.manager': 'Manager',
    'contacts.address': 'Address',
    'contacts.serviceTimes': 'Service Times',
    'contacts.parking': 'Parking available near the church',
    'contacts.parkingAvailable': 'Parking available on church grounds',
    'contacts.socialMedia': 'Social Media',
    'contacts.youthAccounts': 'Youth accounts',

    // Donations Section
    'donations.title': 'Donations',
    'donations.subtitle': 'Your donations help us serve the community and share the Good News',
    'donations.bankDetails': 'Bank Details',
    'donations.recipient': 'Recipient',
    'donations.bank': 'Bank',
    'donations.thankYou': 'Thank you for your generosity and support of the church ministry!',
    'donations.footer': 'Support the church ministry',
    'donations.cta': 'Donate',

    // Footer
    'footer.rights': 'All rights reserved.',
    'footer.church': '"Salvation Temple" Church',
    'footer.copyright': '© 2026-2027 Wholesome Life. All rights reserved.',
    'footer.scanQR': 'Scan to register',
    
    // ===== TRAINING PROGRAM TRANSLATIONS =====
    // Hero
    'hero.year': '2026-2027',
    'hero.dates': '19.09 — 22.05',
    'hero.time': '10:00 — 14:00',
    'hero.age': '18 - 50 YEARS',
    'hero.rhythm': '1 SATURDAY PER MONTH',
    'hero.title': 'WHOLESOME LIFE',
    'hero.subtitle': 'A practical course for those who want to build a solid foundation in an era of change, based on biblical principles and practical foundation.',
    'hero.cta': 'Registration Open',
    
    // Philosophy
    'philosophy.title': 'Course Purpose & Philosophy',
    'philosophy.text': 'To train leaders and the church in biblical truths for finding inner peace and balance in the most important areas of life, as well as to connect with God for obtaining Shalom. Every person is called to find their fullness of life and dwell in peace. The result is a clear action plan for how to fulfill yourself in every important area of life according to God\'s design.',
    
    // Benefits
    'benefits.title': 'What Will You Gain?',
    'benefits.clarity.title': 'Clarity of Calling',
    'benefits.clarity.text': 'Stop living on autopilot. Define your mission and understand where God is calling you in this season.',
    'benefits.core.title': 'Inner Core',
    'benefits.core.text': 'Develop resilience to stress, burnout, and anxiety by relying on eternal truths.',
    'benefits.wisdom.title': 'Practical Wisdom',
    'benefits.wisdom.text': 'Get working tools: simple but powerful things that can change your life for the better.',
    'benefits.connections.title': 'Deep Connections',
    'benefits.connections.text': 'Find friends and mentors with whom you can be authentic and grow together.',
    
    // Target
    'target.title': 'Who Is This For?',
    'target.text': 'This course is for leaders, active parishioners, and everyone who strives for a conscious life and wants to find balance (ages 18-50).',
    'target.checklist.title': 'This is for you if:',
    'target.persona.1': 'I have a vision but don\'t know how to achieve it',
    'target.persona.2': 'I set the same goals but keep failing',
    'target.persona.3': 'I know what I want and how to do it, but I need support',
    'target.persona.4': 'I am a different person at church, work, and home',
    'target.persona.5': 'I seem successful but don\'t know what for',
    'target.persona.6': 'I\'m successful in career but broken at home (or happy at home but struggling financially)',
    'target.persona.7': 'I don\'t have my priorities straight or I\'m struggling with one aspect of the balance wheel',
    'target.persona.8': 'I don\'t want to grow but my inner voice / God says I need to change, and I postpone it, I\'m not at peace',
    
    // Method
    'method.title': 'How We Learn',
    'method.subtitle': 'We use Impact Based Learning method. Minimum lectures, more work on reflection, practice, discussions, and habit formation.',
    'method.theory.title': 'Brief Theory',
    'method.theory.text': 'Biblical truth + World theoretical knowledge adapted for our context.',
    'method.apply.title': 'Theory Application',
    'method.apply.text': 'You leave with a completed plan, not just an idea.',
    'method.groups.title': 'Small Groups',
    'method.groups.text': 'Honest feedback, prayer, and case discussion in a safe environment.',
    'method.mentor.title': 'Mentoring & Practice',
    'method.mentor.text': 'Assignments between modules for implementing skills in real life (family, work).',
    
    // Approach
    'approach.title': 'Our Approach',
    'approach.1.title': 'Awareness',
    'approach.1.text': 'How does God see this? What does He want for this area?',
    'approach.2.title': 'Goal',
    'approach.2.text': 'Where do you want to be and what is the gap between current and desired?',
    'approach.3.title': 'Skills',
    'approach.3.text': 'Tools: Biblical wisdom and practical methods.',
    'approach.4.title': 'Action Plan',
    'approach.4.text': 'What specific steps will you take?',
    'approach.5.title': 'Reinforcement',
    'approach.5.text': 'Support environment and habits for long-term changes.',
    
    // Wheel
    'wheel.title': 'Biblical Balance',
    'wheel.subtitle': 'We don\'t divide life into "spiritual" and "secular". Hover over an area to see its meaning in God\'s design.',
    'wheel.hover': 'Hover over the button above to reveal meaning.',
    'wheel.purpose': 'Purpose',
    'wheel.people': 'People',
    'wheel.body': 'Body',
    'wheel.mind': 'Mind',
    'wheel.finance': 'Finances',
    'wheel.character': 'Character',
    'wheel.church': 'Church',
    'wheel.piety': 'Piety',
    'wheel.shalom': 'SHALOM',
    'wheel.purpose.desc': 'Your unique calling and mission in this world.',
    'wheel.people.desc': 'Relationships, family, and community around you.',
    'wheel.body.desc': 'Physical health — your body as a temple of the Spirit.',
    'wheel.mind.desc': 'Renewing of the mind, thinking, and personal growth.',
    'wheel.finance.desc': 'Managing resources as a good steward.',
    'wheel.character.desc': 'Fruit of the Spirit and habit formation.',
    'wheel.church.desc': 'Your place in the Body of Christ and ministry.',
    'wheel.piety.desc': 'Closeness with God, prayer, and spiritual practices.',
    'wheel.purpose.quote': '"For we are His workmanship, created in Christ Jesus for good works" — Eph. 2:10',
    'wheel.people.quote': '"Love your neighbor as yourself" — Matt. 22:39',
    'wheel.body.quote': '"Your body is a temple of the Holy Spirit" — 1 Cor. 6:19',
    'wheel.mind.quote': '"Be transformed by the renewing of your mind" — Rom. 12:2',
    'wheel.finance.quote': '"Whoever is faithful in little is faithful in much" — Luke 16:10',
    'wheel.character.quote': '"The fruit of the Spirit is love, joy, peace, patience..." — Gal. 5:22',
    'wheel.church.quote': '"You are the body of Christ, and individually members" — 1 Cor. 12:27',
    'wheel.piety.quote': '"Draw near to God, and He will draw near to you" — James 4:8',
    
    // Calendar
    'calendar.title': 'Session Calendar',
    'calendar.subtitle': 'Course dates from September 2026 to June 2027',
    'calendar.break': 'Winter Break',
    
    // Sessions
    'sessions.title': 'Session Program',
    'sessions.about': 'ABOUT SESSION',
    'sessions.tools': 'TOOLS',
    'sessions.break': 'Winter Break (December - January)',
    
    'session.1.month': 'SEPTEMBER',
    'session.1.date': 'SEP 19',
    'session.1.title': '1. Purpose',
    'session.1.about': 'Program start. We will conduct a deep audit of your life and determine the gap between where you are and where God wants to see you.',
    'session.1.tools': 'Balance Wheel (Biblical version)\nIkigai Framework for finding calling\nWriting "Letter from the Future"',
    
    'session.2.month': 'OCTOBER',
    'session.2.date': 'OCT 17',
    'session.2.title': '2. People & Relationships',
    'session.2.about': 'We will learn to talk about difficult things without aggression and set boundaries that preserve love and respect.',
    'session.2.tools': 'Non-Violent Communication (NVC)\nRelationship Audit\nScripts for setting boundaries',
    
    'session.3.month': 'NOVEMBER',
    'session.3.date': 'NOV 21',
    'session.3.title': '3. Body & Health',
    'session.3.about': 'Your body is a Temple. We will explore the physiology of energy, sleep, and nutrition.',
    'session.3.tools': 'Sleep hygiene protocol\nCreating "Joyful Movement Menu"\nAnalysis of daily energy peaks',
    
    'session.4.month': 'DECEMBER',
    'session.4.date': 'DEC 12',
    'session.4.title': '4. Personal Growth & Career',
    'session.4.about': 'Working with mindset. How do our beliefs sabotage us? We will learn to "renew the mind" (Rom 12:2).',
    'session.4.tools': 'Fear Setting technique (Tim Ferriss)\nCognitive reframing of beliefs',
    
    'session.5.month': 'JANUARY',
    'session.5.date': 'JAN 30',
    'session.5.title': '5. Character & Habits',
    'session.5.about': 'Character is the sum of your habits. We will implement the science of habit formation.',
    'session.5.tools': 'Habit Loop (Atomic Habits)\nHabit Stacking\nSMART goals',
    
    'session.6.month': 'FEBRUARY',
    'session.6.date': 'FEB 20',
    'session.6.title': '6. Finances & Management',
    'session.6.about': 'We will move from survival stress to the joy of managing Kingdom resources.',
    'session.6.tools': 'Budget "black holes" audit\nEnvelope method (digital)\nGenerosity plan',
    
    'session.7.month': 'MARCH',
    'session.7.date': 'MAR 20',
    'session.7.title': '7. Church',
    'session.7.about': 'How to find your place in the Body of Christ and turn your home into a place of ministry?',
    'session.7.tools': 'Spiritual gifts test\nHospitality practice',
    
    'session.8.month': 'APRIL',
    'session.8.date': 'APR 24',
    'session.8.title': '8. Piety & Shalom',
    'session.8.about': 'The art of slowing down and hearing God in a noisy world.',
    'session.8.tools': 'Lectio Divina (Prayerful reading)\nSabbath practice\nYear review',
    
    'session.9.month': 'MAY',
    'session.9.date': 'MAY 22',
    'session.9.title': '9. Mind & Emotions',
    'session.9.about': 'Working with emotional intelligence and inner harmony.',
    'session.9.tools': 'Emotional audit\nMindfulness techniques\nYear planning',
    
    'session.10.month': 'JUNE 2027',
    'session.10.date': 'JUN 12',
    'session.10.title': 'FINALE: Reflection & Leaders Evening',
    'session.10.about': 'Final session. Time for deep reflection on the journey, reinforcing useful habits, and celebrating victories together with Leaders Evening.',
    'session.10.tools': 'Year Compass annual review\nReinforcing key habits\nCelebration dinner with leaders',
    
    // Organization
    'org.title': 'Organization & Timing',
    'org.location': 'Location',
    'org.location.value': 'Fish Hall\nLāčplēša 117, Riga\n2nd floor.',
    'org.cost': 'Cost',
    'org.cost.value': 'Covered by "Salvation Temple" church\n+ 10 EUR per session (coffee and snacks)',
    'org.commitment': 'Commitment',
    'org.commitment.value': 'We expect participation in every session.',
    'org.details': 'Details',
    'org.details.value': 'Age: 18 - 50 years\nDates: 19.09.2026 — 12.06.2027\nRhythm: 1 Saturday per month',
    
    // Schedule
    'schedule.title': 'Saturday Schedule',
    'schedule.welcome': 'Welcome',
    'schedule.welcome.desc': 'Check-in: "One word describing your week". Coffee.',
    'schedule.part1': 'Part 1: Awareness',
    'schedule.part1.desc': 'God\'s view: Reading Scripture Anchor.\n"Where are you now on a scale of 1-10?" Defining the gap.',
    'schedule.part2': 'Part 2: Skills',
    'schedule.part2.desc': 'Theory and Demo: Key tool through a biblical lens.',
    'schedule.coffee': 'Coffee Break',
    'schedule.coffee.desc': 'Unstructured time for fellowship.',
    'schedule.part3': 'Part 3: Workshop',
    'schedule.part3.desc': 'Deep dive into theory and practical meaning with group discussions.',
    'schedule.part4': 'Part 4: Reinforcement',
    'schedule.part4.desc': 'Pen and Paper: Filling worksheets. Work in small groups (2-3 people).',
    'schedule.checkout': 'Check-out',
    'schedule.checkout.desc': 'Homework for the month. "Your one next step?"',
    
    // Team
    'team.title': 'Team',
    'team.elya.name': 'Elya Fayzulina',
    'team.elya.role': 'BODY & HEALTH',
    'team.elya.desc': 'Will teach you to treat your body as a temple: energy, sleep, and healthy movement.',
    'team.alex.name': 'Alexander Zvirid',
    'team.alex.role': 'CHURCH & SOCIETY',
    'team.alex.desc': 'Will reveal the topic of ministry, leadership, and creating a godly environment around yourself.',
    'team.tanya.name': 'Tanya Abramova',
    'team.tanya.role': 'RELATIONSHIPS & SPIRIT',
    'team.tanya.desc': 'With deep spiritual practices of abiding in God.',
    'team.sasha.name': 'Sasha Abramov',
    'team.sasha.role': 'PURPOSE',
    'team.sasha.desc': 'Will guide you through the process of finding personal mission and strategic life vision.',
    'team.richards.name': 'Richards Garanchs',
    'team.richards.role': 'FINANCES & CHARACTER',
    'team.richards.desc': 'Will help you organize your budget and build "atomic habits" for long-term growth.',
    'team.victoria.name': 'Victoria Garancha',
    'team.victoria.role': 'MIND & CAREER',
    'team.victoria.desc': 'Will teach you to overcome fears and limiting beliefs.',
  },
  lv: {
    // Church Info
    'church.name': 'Pestīšanas Templis',
    'church.officialName': 'Rīgas Misionāru baptistu draudze',
    'church.shortName': 'Evaņģēliskā draudze',
    'church.tagline': 'Evaņģēliskā draudze Rīgā',
    'church.welcome': 'Laipni lūdzam mūsu mājās! Mēs esam dzīva ticīgo kopiena, ko vieno mīlestība pret Kristu. Šeit ikviens atradīs atbalstu, iedvesmu un ceļu uz garīgo izaugsmi.',
    'church.shortDesc': 'Evaņģēliskā kristīgā draudze, kas kalpo Rīgai ar mīlestību un ticību.',
    'church.serviceSunday': 'Svētdiena 11:00',
    'church.serviceWednesday': 'Trešdiena 18:00',
    'church.serviceLanguages': 'Krievu un Latviešu',
    'church.planVisit': 'Apmeklēt mūs',
    'church.watchLive': 'Skatīties tiešsaistē',

    // Hero Changing Texts
    'hero.comeAndSee': 'Nāc un Skaties',
    'hero.changed': 'Mainītas',
    'hero.word.hearts': 'Sirdis',
    'hero.word.lives': 'Dzīves',
    'hero.word.relationships': 'Attiecības',
    'hero.word.minds': 'Domas',
    'hero.word.personality': 'Raksturi',
    'hero.word.values': 'Vērtības',
    'hero.word.eternities': 'Mūžības',
    'hero.changing.hearts': 'Mainītas Sirdis',
    'hero.changing.lives': 'Mainītas Dzīves',
    'hero.changing.relationships': 'Mainītas Attiecības',
    'hero.changing.minds': 'Mainīta Domāšana',
    'hero.changing.personality': 'Mainīts Raksturs',
    'hero.changing.values': 'Mainītas Vērtības',
    'hero.changing.eternities': 'Mainītas Mūžības',

    // Church Welcome
    'church.heroWelcome': 'Piedzīvojiet Dieva klātbūtni draudzē šajā svētdienā.',

    // Navigation
    'nav.about': 'Par mums',
    'nav.history': 'Vēsture',
    'nav.events': 'Notikumi',
    'nav.ministries': 'Kalpošanas',
    'nav.testimonies': 'Liecības',
    'nav.contacts': 'Kontakti',
    'nav.donations': 'Ziedojumi',
    'nav.program': 'Programma',
    'nav.calendar': 'Kalendārs',
    'nav.team': 'Komanda',
    'nav.register': 'Reģistrācija',

    // About Section
    'about.title': 'Par Mums',
    'about.subtitle': 'Iepazīstiet mūsu draudzi, tās vīziju un vērtības',
    'about.intro': 'Pestīšanas Templis — vieta, kur cilvēki garīgi nostiprinās un mācās izplatīt Evaņģēliju.',
    'about.getToKnowUs': 'Iepazīties ar mums',
    'about.vision.title': 'Mūsu Vīzija',
    'about.vision.text': 'Pestīšanas Templis slavē Dievu, radot un audzinot mācekļus, kuri pilnībā apmācīti Kristū Rīgas Latgales reģionā, kuri savukārt rada jaunus mācekļus, kas noved pie jaunas draudzes dibināšanas Latvijā.',
    'about.vision.textShort': 'Pestīšanas Templis slavē Dievu, radot un audzinot mācekļus, kuri pilnībā apmācīti Kristū Rīgas Latgales reģionā, kuri savukārt rada jaunus mācekļus, kas noved pie jaunas draudzes dibināšanas Latvijā.',
    'about.values.title': 'Mūsu Vērtības',
    'about.values.christ.title': 'Kristus ir mūsu centrs',
    'about.values.christ.paragraph': 'Kristus ir mūsu centrs un fokuss visā, ko darām. Mēs atceramies, kas Viņš bija un ko Viņš darīja, kā arī to, ko Viņš dara tagad caur Svēto Garu.',
    'about.values.bible.title': 'Bībele ir mūsu patiesība',
    'about.values.bible.paragraph': 'Dieva Vārds ir mūsu ticības pamats. Evaņģēlijs un visas Bībeles grāmatas vada mūsu dzīvi un kalpošanu.',
    'about.values.discipleship.title': 'Māceklība',
    'about.values.discipleship.paragraph': 'Mēs augam caur mentoringu un sadraudzību garīgai izaugsmei, palīdzot viens otram kļūt par nobriedušiem Kristus sekotājiem.',
    'about.values.mission.title': 'Misija',
    'about.values.mission.paragraph': 'Mēs dalāmies ar labo vēsti vārdos un darbos, parādot Dieva mīlestību praktiskā kalpošanā apkārtējiem.',
    'about.mission.title': 'Mūsu Misija',
    'about.mission.text': 'Pestīšanas Templis — vieta, kur cilvēki garīgi nostiprinās un mācās izplatīt Evaņģēliju.',
    'about.historyButton': 'Uzzināt mūsu vēsturi',


    // History Section
    'history.title': 'Draudzes Vēsture',
    'history.subtitle': 'Pestīšanas Templis — lielākais baptistu dievnams Latvijā ar bagātu vēsturi',
    'history.founder': 'Dibinātājs',
    'history.fetler.name': 'Viljams Fetlers',
    'history.fetler.desc': 'OBDS idejiskais līderis, kas lielu uzmanību veltīja evaņģelizācijai, īpaši Latgalē, kā arī misijas darbam krievu, poļu un citu etnisko minoritāšu vidū.',
    'history.fetler.caption': 'Viljams Fetlers un Daugavpils Baltā baznīca — viņa Latgales misijas darba auglis',
    'history.obds.title': 'Otrā Baptistu Draudžu Savienība (OBDS)',
    'history.obds.text': 'Pēc šķelšanās "atmodas baptisti" izveidoja Otro Baptistu Draudžu Savienību (OBDS). Rīgā pie OBDS piederēja Mateja, Āgenskalna, Atmodas (Pestīšanas Templis) un Golgātas draudzes. 1929.gadā LBDS bija 77 draudzes ar 6766 locekļiem, bet OBDS 39 draudzes ar 3763 locekļiem. Plašā evaņģelizācijas darba dēļ OBDS locekļu skaits auga straujāk.',
    'history.evangelization.title': 'Evaņģelizācija un Misija',
    'history.evangelization.text': 'Evaņģēlija pasludināšanai OBDS izmantoja kinozāles, tautas namus, tirgus laukumus un citas publiskas vietas. Rīgā un Liepājā tika sarīkoti plaši Bībeles gājieni. Kristības notika dažādās publiskās vietās jūras malā, ezeru un upju krastos.',
    'history.tent.caption': 'Augšā — OBDS Bībeles gājiens Rīgas ielās; apakšā — evaņģelizācijas telts Pestīšanas Tempļa pagalmā',
    'history.temple.title': 'Pestīšanas Templis',
    'history.temple.text': '1927.gadā Rīgā, Lāčplēša ielā 117, tika pabeigts lielākais baptistu dievnams — Pestīšanas Templis. Atklāšanā piedalījās daudzi prominenti viesi, tostarp ASV un Lielbritānijas vēstnieki Latvijā. Lielākā zāle spēja uzņemt vairāk nekā 2000 cilvēkus. Dievkalpojumi notika četrās valodās — latviešu, krievu, vācu un poļu.',
    'history.building.caption': 'Pestīšanas Templis — lielākais baptistu dievnams Latvijā, 1927.g.',

    // Statistics
    'statistics.title': 'Mūsu Kopiena',
    'statistics.subtitle': 'Mēs esam ticīgo ģimene dažādu vecumu un paaudžu',
    'statistics.total': 'Kopā locekļu',
    'statistics.members.hover': 'Mēs esam dažāda kopiena ar 150 cilvēkiem no visām vecuma grupām un dzīves jomām. Bērni, jaunieši, ģimenes un seniori kopā slavē Dievu.',
    'statistics.pastYear.title': 'Mūsu draudze pagājušajā gadā skaitļos',
    'statistics.history.title': 'Draudzes vēsturē kopā',
    'statistics.history.baptisms': 'Kristības',
    'statistics.history.sundaySchool': 'Bērni svētdienas skolā',
    'statistics.history.summerCamps': 'Vasaras nometņu dalībnieki',
    'statistics.history.families': 'Ģimenes saņēma palīdzību',
    'statistics.history.childrenCare': 'Bērni saņēma rūpes un uzmanību',
    'statistics.baptisms': 'Kristības',
    'statistics.baptisms.hover': 'Pagājušajā gadā 12 cilvēki tika kristīti. Nākamā kristība notiks 2026. gada 9. maijā. Sazinieties ar mācītāju, ja vēlaties sagatavoties kristībām.',
    'statistics.baptisms.learnMore': 'Uzzināt par kristībām',
    'statistics.sundaySchoolPeople': 'Svētdienas skolā',
    'statistics.sundaySchool.hover': 'Katru svētdienu 80 bērni mācās Bībeli aizraujošā veidā. Nodarbības notiek dievkalpojuma laikā dažādu vecumu bērniem.',
    'statistics.sundaySchool.learnMore': 'Uzzināt par svētdienas skolu',
    'statistics.summerCamp': 'Vasaras nometnēs',
    'statistics.summerCamp.hover': 'Katru vasaru 90 bērni un pusaudži piedalās mūsu nometnēs, kur iepazīst Dievu caur spēlēm, radošumu un sadraudzību.',
    'statistics.summerCamp.learnMore': 'Uzzināt par vasaras nometnēm',
    'statistics.childrenGifts': 'Bērni saņēma dāvanas',
    'statistics.childrenGifts.hover': 'Ziemassvētku akcijas ietvaros 800 bērni no trūcīgām ģimenēm saņēma dāvanas un uzzināja par Dieva mīlestību.',
    'statistics.familiesHelped': 'Ģimenes saņēma palīdzību',
    'statistics.familiesHelped.hover': 'Caur "Mīlestības un Rūpju" kalpošanu mēs palīdzam ģimenēm ar pārtiku, apģērbu un praktisku atbalstu.',
    'statistics.childrenSchool': 'Bērni sagatavoti skolai',
    'statistics.childrenSchool.hover': 'Katru gadu mēs palīdzam bērniem no trūcīgām ģimenēm sagatavoties skolai, nodrošinot viņus ar nepieciešamajiem piederumiem.',

    // Gallery
    'gallery.title': 'Galerija',
    'gallery.subtitle': 'Mirkļi no mūsu draudzes dzīves',
    'gallery.pageTitle': 'Pestīšanas Tempļa Fotogalerija',
    'gallery.pageSubtitle': 'Prieka, ticības un vienotības mirkļi mūsu kopienā',
    'gallery.followUs': 'Sekojiet mums sociālajos tīklos',
    'gallery.viewAll': 'Skatīt visu galeriju',
    
    // History extended (Latvian)
    'history.fetler.extended': 'Jau neatkarīgajā Latvijā Fetlers varēja sludināt vēsti par pestīšanu visur — radio, kinoteātros, pilsētas parkos, upju piestātnēs, cietumos, kapsētās un kāzās.',
    'history.return.title': 'Atgriešanās Dzimtenē',
    'history.return.text': 'Viljams Fetlers atgriezās Latvijā 1923. gadā. Latvija bija kļuvusi par neatkarīgu valsti ar ticības un sludināšanas brīvību. Tāpēc vēsti par pestīšanu Jēzū Kristū varēja sludināt visur.',
    'history.temple.details': 'Pestīšanas Templī bija vairākas zāles, no kurām lielākajā varēja sapulcēties vairāk nekā 2000 cilvēku. Dievkalpojumi notika četrās valodās — latviešu, krievu, vācu un poļu.',
    'history.interior.title': 'Kalpošana Templī',
    'history.interior.text': 'Dievkalpojumi ilga trīs līdz sešas stundas, taču Svētā Gara uguns bija tik jūtama, ka laiks pagāja nemanāmi. Tempļa tornī darbojās lūgšanu sardze — 24 stundas diennaktī cilvēki lūdza par atmodu Latvijā.',
    'history.interior.caption': 'Pestīšanas Tempļa Lielā zāle dievkalpojuma laikā',
    'history.evangelization.label': 'Evaņģelizācija',
    'history.legacy.title': 'Ticības Mantojums',
    'history.legacy.text': 'Šodien Pestīšanas Templis turpina misiju, kas aizsākta gandrīz pirms 100 gadiem — slavēt Dievu un audzināt Kristus mācekļus. Mēs glabājam bagātu garīgo mantojumu un ar ticību raugāmies nākotnē.',
    'history.resources.title': 'Vēsturiskie Resursi',
    'history.resources.fetlerArticle': 'Raksts par Viljamu Fetleru',
    'history.resources.lbcHistory': 'LBC Vēsture',
    'history.resources.encyclopedia': 'Enciklopēdija: Baptisti Latvijā',
    'history.resources.lostLatvia': 'Zudusī Latvija: Pestīšanas Templis',

    // Testimonies Section
    'testimonies.title': 'Liecības',
    'testimonies.subtitle': 'Stāsti par mainītām dzīvēm',
    'testimonies.viewAll': 'Lasīt visas liecības',
    'testimonies.before': 'Pirms',
    'testimonies.encounter': 'Tikšanās ar Kristu',
    'testimonies.after': 'Pēc',
    'testimonies.share': 'Vēlaties dalīties ar savu stāstu?',
    'testimonies.shareButton': 'Sazinieties ar mums',
    'testimonies.testimony1.name': 'Marija K.',
    'testimonies.testimony1.summary': 'Dievs mainīja manu dzīvi, kad es atnācu uz šo draudzi...',
    'testimonies.testimony1.before': 'Es dzīvoju pastāvīgā trauksmē un neatradu dzīves jēgu.',
    'testimonies.testimony1.encounter': 'Draugi uzaicināja mani uz dievkalpojumu, un es pirmo reizi sajutu Dieva mīlestību.',
    'testimonies.testimony1.after': 'Šodien es dzīvoju ar mieru sirdī un kalpoju svētdienas skolā.',
    'testimonies.testimony2.name': 'Aleksejs P.',
    'testimonies.testimony2.summary': 'No atkarības uz brīvību Kristū...',
    'testimonies.testimony2.before': 'Atkarība iznīcināja manu ģimeni un karjeru.',
    'testimonies.testimony2.encounter': 'Mācītājs lūdza par mani, un es piedzīvoju atbrīvošanu.',
    'testimonies.testimony2.after': 'Jau 5 gadus esmu brīvs un palīdzu citiem atrast šo ceļu.',
    'testimonies.testimony3.name': 'Jeļena S.',
    'testimonies.testimony3.summary': 'Atradu īstu ģimeni draudzē...',
    'testimonies.testimony3.before': 'Pēc šķiršanās es jutos vientuļa.',
    'testimonies.testimony3.encounter': 'Mājas grupa mani pieņēma kā ģimeni.',
    'testimonies.testimony3.after': 'Tagad es vadu sieviešu kalpošanu un palīdzu citiem.',
    'testimonies.testimony4.name': 'Dmitrijs V.',
    'testimonies.testimony4.summary': 'No ateisma uz ticību...',
    'testimonies.testimony4.before': 'Es biju pārliecināts ateists.',
    'testimonies.testimony4.encounter': 'Bībeles studijas atvēra manas acis patiesībai.',
    'testimonies.testimony4.after': 'Šodien esmu svētdienas skolas skolotājs.',
    'testimonies.testimony5.name': 'Anna L.',
    'testimonies.testimony5.summary': 'Dziedināšana no pagātnes brūcēm...',
    'testimonies.testimony5.before': 'Bērnības traumas neļāva man dzīvot pilnvērtīgi.',
    'testimonies.testimony5.encounter': 'Caur dvēseļu kopšanu es atradu dziedināšanu.',
    'testimonies.testimony5.after': 'Dievs atjaunoja manas attiecības ar ģimeni.',

    // Events
    'events.title': 'Notikumi',
    'events.subtitle': 'Sekojiet līdzi draudzes dzīvei un gaidāmajiem pasākumiem',
    'events.upcoming': 'Tuvākie notikumi',
    'events.prayerMeeting': 'Lūgšana',
    'events.holyCommunion': 'Svētais Vakarēdiens',
    'events.sundayService': 'Svētdienas dievkalpojums',
    'events.baptism.nextDate': 'Nākamās kristības: 2026. gada 9. maijs',
    'events.baptism.contactPastor': 'Sazinieties ar mācītāju, ja vēlaties piedalīties.',
    'events.news.title': 'Jaunumi',
    'events.news.desc': 'Jaunākās ziņas un atjauninājumi no draudzes dzīves',
    'events.news.content': 'Sekojiet mūsu sociālajiem tīkliem, lai uzzinātu jaunākās ziņas.',
    'events.calendar.title': 'Kalendārs',
    'events.calendar.desc': 'Dievkalpojumu un pasākumu grafiks',
    'events.calendar.content': 'Svētdienas dievkalpojums plkst. 11:00, Bībeles studijas trešdienās plkst. 18:00.',
    'events.training.title': 'Mācību pasākumi',
    'events.training.desc': 'Kurss "Pilnvērtīga Dzīve" 2026-2027',
    'events.training.content': 'Praktisks kurss tiem, kuri vēlas veidot stabilu pamatu, balstoties uz Bībeles principiem.',
    'events.training.link': 'Uzzināt vairāk par kursu',
    'events.baptism.title': 'Ūdens kristības',
    'events.baptism.desc': 'Informācija par kristībām un sagatavošanos',
    'events.baptism.content': 'Kristības ir svarīgs ticības solis. Sazinieties ar mums, lai uzzinātu par sagatavošanos kristībām.',

    // Ministries Section
    'ministries.title': 'Kalpošanas',
    'ministries.subtitle': 'Atrodiet savu vietu mūsu kopienā un kalpojiet kopā ar mums',
    'ministries.wantToServe': 'Vēlos kalpot',
    'ministries.leader': 'Vadītājs',
    'ministries.worship.title': 'Dievkalpojumi',
    'ministries.worship.desc': 'Iknedēļas dievkalpojumi un slavēšana',
    'ministries.sundaySchool.title': 'Svētdienas skola',
    'ministries.sundaySchool.desc': 'Bībeles mācības bērniem',
    'ministries.ribaClub.title': 'Riba klubs',
    'ministries.ribaClub.desc': 'Pusaudžu klubs (12-16 gadi)',
    'ministries.youth.title': 'Jauniešu kalpošana',
    'ministries.youth.desc': 'Kalpošana jauniem cilvēkiem',
    'ministries.youngLife.title': 'YoungLife',
    'ministries.youngLife.desc': 'Programma pusaudžiem',
    'ministries.charity.title': 'Labdarība',
    'ministries.charity.desc': 'Palīdzība tiem, kam nepieciešams',
    'ministries.choir.title': 'Koris',
    'ministries.choir.desc': 'Mūzikas kalpošana',
    'ministries.smallGroups.title': 'Mājas grupas',
    'ministries.smallGroups.desc': 'Mazās grupas kopībai',
    'ministries.mensMinistry.title': 'Vīriešu kalpošana',
    'ministries.mensMinistry.desc': 'Brālība un izaugsme vīriešiem',
    'ministries.womensMinistry.title': 'Sieviešu kalpošana',
    'ministries.womensMinistry.desc': 'Kopība un atbalsts sievietēm',
    'ministries.loveAndCare.title': 'Mīlestība un Rūpes',
    'ministries.loveAndCare.desc': 'Praktiska palīdzība un rūpes',
    'ministries.media.title': 'Mediju komanda',
    'ministries.media.desc': 'Tehniskā un mediju kalpošana',
    'ministries.serve.title': 'Vēlos kalpot',
    'ministries.serve.desc': 'Atrodi savu kalpošanu',

    // Care Section
    'care.title': 'Rūpes un Atbalsts',
    'care.subtitle': 'Mēs esam šeit, lai atbalstītu jūs jebkurā dzīves situācijā',
    'care.prayer.title': 'Lūgšanu atbalsts',
    'care.prayer.desc': 'Nosūtiet mums savu lūgšanas vajadzību, un mēs lūgsimies kopā ar jums.',
    'care.prayer.cta': 'Nosūtīt lūgumu',
    'care.counseling.title': 'Dvēseļu kopšana',
    'care.counseling.desc': 'Mācītāja konsultācijas tiem, kam nepieciešams garīgs atbalsts un vadība.',
    'care.counseling.cta': 'Pieteikties',

    // Contacts Section
    'contacts.title': 'Kontakti',
    'contacts.pastor': 'Mācītājs',
    'contacts.manager': 'Pārvaldnieks',
    'contacts.address': 'Adrese',
    'contacts.serviceTimes': 'Dievkalpojumu laiki',
    'contacts.parking': 'Autostāvvieta pieejama netālu no draudzes',
    'contacts.parkingAvailable': 'Autostāvvieta pieejama draudzes teritorijā',
    'contacts.socialMedia': 'Sociālie tīkli',
    'contacts.youthAccounts': 'Jauniešu konti',

    // Donations Section
    'donations.title': 'Ziedojumi',
    'donations.subtitle': 'Jūsu ziedojumi palīdz mums kalpot kopienai un nest Labo Vēsti',
    'donations.whyGive': 'Kāpēc ziedot?',
    'donations.whyGiveText': 'Jūsu ziedojumi atbalsta draudzes kalpošanu, palīdz tiem, kam tas nepieciešams, un izplata Evaņģēliju.',
    'donations.bankDetails': 'Bankas rekvizīti',
    'donations.recipient': 'Saņēmējs',
    'donations.bank': 'Banka',
    'donations.thankYou': 'Paldies par jūsu dāsnumu un draudzes kalpošanas atbalstu!',
    'donations.footer': 'Atbalstiet draudzes kalpošanu',
    'donations.cta': 'Ziedot',
    'donations.impact': 'Kā tiek izmantoti ziedojumi',
    'donations.impactBuilding': 'Draudzes ēkas uzturēšana',
    'donations.impactMinistries': 'Kalpošanu atbalsts',
    'donations.impactCharity': 'Labdarības darbs',

    // Footer
    'footer.rights': 'Visas tiesības aizsargātas.',
    'footer.aboutText': 'Vieta, kur cilvēki garīgi nostiprinās un mācās izplatīt Evaņģēliju.',
    'footer.navigation': 'Navigācija',
    'footer.resources': 'Resursi',
    'footer.church': 'Draudze "Pestīšanas Templis"',
    'footer.copyright': '© 2026-2027 Pilnvērtīga Dzīve. Visas tiesības aizsargātas.',
    'footer.scanQR': 'Skenējiet, lai reģistrētos',
    
    // ===== TRAINING PROGRAM TRANSLATIONS =====
    // Hero
    'hero.year': '2026-2027',
    'hero.dates': '19.09 — 22.05',
    'hero.time': '10:00 — 14:00',
    'hero.age': '18 - 50 GADI',
    'hero.rhythm': '1 SESTDIENA MĒNESĪ',
    'hero.title': 'PILNVĒRTĪGA DZĪVE',
    'hero.subtitle': 'Praktisks kurss tiem, kuri vēlas veidot stabilu pamatu pārmaiņu laikmetā, balstoties uz Bībeles principiem un praktisku pamatu.',
    'hero.cta': 'Reģistrācija atvērta',
    
    // Philosophy
    'philosophy.title': 'Kursa mērķis un filozofija',
    'philosophy.text': 'Apmācīt līderus un draudzi Bībeles patiesībās, lai iegūtu iekšēju mieru un līdzsvaru svarīgākajās dzīves jomās, kā arī savienoties ar Dievu, lai iegūtu Šalomu. Katrs cilvēks ir aicināts atrast savu pilnvērtīgo dzīvi un dzīvot mierā. Rezultāts ir skaidrs rīcības plāns, kā realizēt sevi katrā svarīgā dzīves jomā saskaņā ar Dieva nodomu.',
    
    // Benefits
    'benefits.title': 'Ko jūs iegūsiet?',
    'benefits.clarity.title': 'Aicinājuma skaidrība',
    'benefits.clarity.text': 'Beidz dzīvot pēc inerces. Nosaki savu misiju un saproti, kurp Dievs tevi aicina šajā sezonā.',
    'benefits.core.title': 'Iekšējais stingums',
    'benefits.core.text': 'Attīsti noturību pret stresu, izdegšanu un trauksmi, balstoties uz mūžīgām patiesībām.',
    'benefits.wisdom.title': 'Praktiskā gudrība',
    'benefits.wisdom.text': 'Iegūsti strādājošus rīkus: vienkāršas, bet spēcīgas lietas, kas var mainīt tavu dzīvi uz labo pusi.',
    'benefits.connections.title': 'Dziļas saites',
    'benefits.connections.text': 'Atrodi draugus un mentorus, ar kuriem vari būt īsts un augt kopā.',
    
    // Target
    'target.title': 'Kam tas ir domāts?',
    'target.text': 'Šis kurss ir līderiem, aktīviem draudzes locekļiem un visiem, kas tiecas pēc apzinātas dzīves un vēlas atrast līdzsvaru (18-50 gadi).',
    'target.checklist.title': 'Tas ir tev, ja:',
    'target.persona.1': 'Man ir vīzija, bet es nezinu, kā to sasniegt',
    'target.persona.2': 'Es izvirzu vienus un tos pašus mērķus, bet cieš neveiksmi',
    'target.persona.3': 'Es zinu, ko gribu un kā to izdarīt, bet man vajag atbalstu',
    'target.persona.4': 'Es esmu atšķirīgs cilvēks draudzē, darbā un mājās',
    'target.persona.5': 'Es šķietami esmu veiksmīgs, bet nezinu, kāpēc',
    'target.persona.6': 'Es esmu veiksmīgs karjerā, bet salauzts mājās (vai laimīgs mājās, bet finansiāli grūtības)',
    'target.persona.7': 'Man nav sakārtotas prioritātes vai es cīnos ar kādu līdzsvara rata aspektu',
    'target.persona.8': 'Es negribu augt, bet iekšējā balss / Dievs saka, ka man jāmainās, un es to atliek, es neesmu mierā',
    
    // Method
    'method.title': 'Kā mēs mācāmies',
    'method.subtitle': 'Mēs izmantojam Impact Based Learning metodi. Minimums lekciju, vairāk darba pie refleksijas, prakses, diskusijām un paradumu veidošanas.',
    'method.theory.title': 'Īsa teorija',
    'method.theory.text': 'Bībeles patiesība + Pasaules teorētiskās zināšanas, pielāgotas mūsu kontekstam.',
    'method.apply.title': 'Teorijas pielietojums',
    'method.apply.text': 'Tu aizej ar aizpildītu plānu, nevis tikai ideju.',
    'method.groups.title': 'Mazās grupas',
    'method.groups.text': 'Godīga atgriezeniskā saite, lūgšana un gadījumu apspriešana drošā vidē.',
    'method.mentor.title': 'Mentorings un prakse',
    'method.mentor.text': 'Uzdevumi starp moduļiem, lai ieviestu prasmes reālajā dzīvē (ģimene, darbs).',
    
    // Approach
    'approach.title': 'Mūsu pieeja',
    'approach.1.title': 'Apzinātība',
    'approach.1.text': 'Kā Dievs to redz? Ko Viņš vēlas šai jomai?',
    'approach.2.title': 'Mērķis',
    'approach.2.text': 'Kur tu vēlies būt un kāda ir plaisa starp pašreizējo un vēlamo?',
    'approach.3.title': 'Prasmes',
    'approach.3.text': 'Rīki: Bībeles gudrība un praktiskas metodes.',
    'approach.4.title': 'Rīcības plāns',
    'approach.4.text': 'Kādus konkrētus soļus tu speršu?',
    'approach.5.title': 'Nostiprināšana',
    'approach.5.text': 'Atbalstoša vide un paradumi ilgtermiņa izmaiņām.',
    
    // Wheel
    'wheel.title': 'Bībeles līdzsvars',
    'wheel.subtitle': 'Mēs nešķiram dzīvi "garīgajā" un "laicīgajā". Virziet kursoru uz jomu, lai redzētu tās nozīmi Dieva nodomā.',
    'wheel.hover': 'Virziet kursoru uz pogu, lai atklātu nozīmi.',
    'wheel.purpose': 'Mērķis',
    'wheel.people': 'Cilvēki',
    'wheel.body': 'Ķermenis',
    'wheel.mind': 'Prāts',
    'wheel.finance': 'Finanses',
    'wheel.character': 'Raksturs',
    'wheel.church': 'Draudze',
    'wheel.piety': 'Dievbijība',
    'wheel.shalom': 'ŠALOMS',
    'wheel.purpose.desc': 'Tavs unikālais aicinājums un misija šajā pasaulē.',
    'wheel.people.desc': 'Attiecības, ģimene un kopiena ap tevi.',
    'wheel.body.desc': 'Fiziskā veselība — tavs ķermenis kā Gara templis.',
    'wheel.mind.desc': 'Prāta atjaunošana, domāšana un personīgā izaugsme.',
    'wheel.finance.desc': 'Resursu pārvaldība kā labam pārvaldniekam.',
    'wheel.character.desc': 'Gara augļi un paradumu veidošana.',
    'wheel.church.desc': 'Tava vieta Kristus Miesā un kalpošana.',
    'wheel.piety.desc': 'Tuvība ar Dievu, lūgšana un garīgās prakses.',
    'wheel.purpose.quote': '"Jo mēs esam Viņa darbs, Kristū Jēzū radīti labiem darbiem" — Ef. 2:10',
    'wheel.people.quote': '"Mīli savu tuvāko kā sevi pašu" — Mt. 22:39',
    'wheel.body.quote': '"Jūsu miesa ir Svētā Gara templis" — 1.Kor. 6:19',
    'wheel.mind.quote': '"Pārvērtieties, atjaunodami savu prātu" — Rom. 12:2',
    'wheel.finance.quote': '"Kas ir uzticams mazumā, tas arī lielumā ir uzticams" — Lk. 16:10',
    'wheel.character.quote': '"Bet Gara auglis ir: mīlestība, prieks, miers, pacietība..." — Gal. 5:22',
    'wheel.church.quote': '"Jūs esat Kristus miesa, un katrs no jums ir tās loceklis" — 1.Kor. 12:27',
    'wheel.piety.quote': '"Tuvojieties Dievam, un Viņš tuvosies jums" — Jēk. 4:8',
    
    // Calendar
    'calendar.title': 'Sesiju kalendārs',
    'calendar.subtitle': 'Kursa datumi no 2026. gada septembra līdz 2027. gada jūnijam',
    'calendar.break': 'Ziemas pārtraukums',
    
    // Sessions
    'sessions.title': 'Sesiju programma',
    'sessions.about': 'PAR SESIJU',
    'sessions.tools': 'RĪKI',
    'sessions.break': 'Ziemas pārtraukums (Decembris - Janvāris)',
    
    'session.1.month': 'SEPTEMBRIS',
    'session.1.date': '19. SEP',
    'session.1.title': '1. Mērķis',
    'session.1.about': 'Programmas sākums. Mēs veiksim dziļu tavas dzīves auditu un noteikt plaisu starp to, kur tu esi, un kur Dievs vēlas tevi redzēt.',
    'session.1.tools': 'Līdzsvara rats (Bībeles versija)\nIkigai ietvars aicinājuma atrašanai\n"Vēstules no nākotnes" rakstīšana',
    
    'session.2.month': 'OKTOBRIS',
    'session.2.date': '17. OKT',
    'session.2.title': '2. Cilvēki un attiecības',
    'session.2.about': 'Mēs mācīsimies runāt par grūtām lietām bez agresijas un noteikt robežas, kas saglabā mīlestību un cieņu.',
    'session.2.tools': 'Nevardarbīgā komunikācija (NVC)\nAttiecību audits\nRobežu noteikšanas skripti',
    
    'session.3.month': 'NOVEMBRIS',
    'session.3.date': '21. NOV',
    'session.3.title': '3. Ķermenis un veselība',
    'session.3.about': 'Tavs ķermenis ir Templis. Mēs izpētīsim enerģijas, miega un uztura fizioloģiju.',
    'session.3.tools': 'Miega higiēnas protokols\n"Priecīgas kustības ēdienkartes" izveide\nDienas enerģijas maksimumu analīze',
    
    'session.4.month': 'DECEMBRIS',
    'session.4.date': '12. DEC',
    'session.4.title': '4. Personīgā izaugsme un karjera',
    'session.4.about': 'Darbs ar domāšanu. Kā mūsu pārliecības mūs sabotē? Mēs mācīsimies "atjaunot prātu" (Rom 12:2).',
    'session.4.tools': 'Fear Setting tehnika (Tim Ferriss)\nPārliecību kognitīvā pārformulēšana',
    
    'session.5.month': 'JANVĀRIS',
    'session.5.date': '30. JAN',
    'session.5.title': '5. Raksturs un paradumi',
    'session.5.about': 'Raksturs ir tavu paradumu summa. Mēs ieviesīsim paradumu veidošanas zinātni.',
    'session.5.tools': 'Paradumu cilpa (Atomic Habits)\nHabit Stacking\nSMART mērķi',
    
    'session.6.month': 'FEBRUĀRIS',
    'session.6.date': '20. FEB',
    'session.6.title': '6. Finanses un pārvaldība',
    'session.6.about': 'Mēs pāriesim no izdzīvošanas stresa uz prieku pārvaldīt Valstības resursus.',
    'session.6.tools': 'Budžeta "melno caurumu" audits\nAplokšņu metode (digitālā)\nDāsnuma plāns',
    
    'session.7.month': 'MARTS',
    'session.7.date': '20. MAR',
    'session.7.title': '7. Draudze',
    'session.7.about': 'Kā atrast savu vietu Kristus Miesā un pārvērst savas mājas par kalpošanas vietu?',
    'session.7.tools': 'Garīgo dāvanu tests\nViesmīlības prakse',
    
    'session.8.month': 'APRĪLIS',
    'session.8.date': '24. APR',
    'session.8.title': '8. Dievbijība un Šaloms',
    'session.8.about': 'Māksla palēnināt un dzirdēt Dievu trokšņainā pasaulē.',
    'session.8.tools': 'Lectio Divina (Lūgšanu lasīšana)\nŠabata prakse\nGada pārskats',
    
    'session.9.month': 'MAIJS',
    'session.9.date': '22. MAI',
    'session.9.title': '9. Prāts un emocijas',
    'session.9.about': 'Darbs ar emocionālo inteliģenci un iekšējo harmoniju.',
    'session.9.tools': 'Emocionālais audits\nApzinātības tehnikas\nGada plānošana',
    
    'session.10.month': 'JŪNIJS 2027',
    'session.10.date': '12. JŪN',
    'session.10.title': 'FINĀLS: Refleksija un Līderu vakars',
    'session.10.about': 'Noslēguma sesija. Laiks dziļai refleksijai par noieto ceļu, noderīgo paradumu nostiprināšanai un uzvaru svinēšanai kopā ar Līderu vakaru.',
    'session.10.tools': 'Year Compass gada pārskats\nGalveno paradumu nostiprināšana\nSvinīgās vakariņas ar līderiem',
    
    // Organization
    'org.title': 'Organizācija un laiks',
    'org.location': 'Vieta',
    'org.location.value': 'Riba zāle\nLāčplēša 117, Rīga\n2. stāvs.',
    'org.cost': 'Izmaksas',
    'org.cost.value': 'Sedz draudze "Pestīšanas Templis"\n+ 10 EUR par sesiju (kafija un uzkodas)',
    'org.commitment': 'Apņemšanās',
    'org.commitment.value': 'Mēs sagaidām dalību katrā sesijā.',
    'org.details': 'Detaļas',
    'org.details.value': 'Vecums: 18 - 50 gadi\nDatumi: 19.09.2026 — 12.06.2027\nRitms: 1 sestdiena mēnesī',
    
    // Schedule
    'schedule.title': 'Sestdienas grafiks',
    'schedule.welcome': 'Sveicināšana',
    'schedule.welcome.desc': 'Reģistrēšanās: "Viens vārds, kas raksturo nedēļu". Kafija.',
    'schedule.part1': '1. daļa: Apzinātība',
    'schedule.part1.desc': 'Dieva skatījums: Rakstu enkura lasīšana.\n"Kur tu tagad esi skalā no 1-10?" Plaisas noteikšana.',
    'schedule.part2': '2. daļa: Prasmes',
    'schedule.part2.desc': 'Teorija un demonstrācija: Galvenais rīks caur Bībeles prizmu.',
    'schedule.coffee': 'Kafijas pārtraukums',
    'schedule.coffee.desc': 'Nestrukturēts laiks kopībai.',
    'schedule.part3': '3. daļa: Praktikums',
    'schedule.part3.desc': 'Dziļa iegremdēšanās teorijā un praktiskajā nozīmē ar grupu diskusijām.',
    'schedule.part4': '4. daļa: Nostiprināšana',
    'schedule.part4.desc': 'Pildspalva un papīrs: Darba lapu aizpildīšana. Darbs mazās grupās (2-3 cilvēki).',
    'schedule.checkout': 'Noslēgums',
    'schedule.checkout.desc': 'Mājas darbs mēnesim. "Tavs viens nākamais solis?"',
    
    // Team
    'team.title': 'Komanda',
    'team.elya.name': 'Eļa Faizulina',
    'team.elya.role': 'ĶERMENIS UN VESELĪBA',
    'team.elya.desc': 'Iemācīs izturēties pret savu ķermeni kā pret templi: enerģija, miegs un veselīga kustība.',
    'team.alex.name': 'Aleksandrs Zvirids',
    'team.alex.role': 'DRAUDZE UN SABIEDRĪBA',
    'team.alex.desc': 'Atklās kalpošanas, līderības tēmu un dievbijīgas vides veidošanu ap sevi.',
    'team.tanya.name': 'Taņa Abramova',
    'team.tanya.role': 'ATTIECĪBAS UN GARS',
    'team.tanya.desc': 'Ar dziļām garīgām praksēm, lai paliktu Dievā.',
    'team.sasha.name': 'Saša Abramovs',
    'team.sasha.role': 'MĒRĶIS',
    'team.sasha.desc': 'Vadīs tevi caur personīgās misijas un stratēģiskās dzīves vīzijas atrašanas procesu.',
    'team.richards.name': 'Rihards Garančs',
    'team.richards.role': 'FINANSES UN RAKSTURS',
    'team.richards.desc': 'Palīdzēs sakārtot budžetu un veidot "atomiskos paradumus" ilgtermiņa izaugsmei.',
    'team.victoria.name': 'Viktorija Garanča',
    'team.victoria.role': 'PRĀTS UN KARJERA',
    'team.victoria.desc': 'Iemācīs pārvarēt bailes un ierobežojošus uzskatus.',
  },
};

// Default translation function for HMR fallback
const defaultT = (key: string): string => key;

// Default context value to prevent HMR crashes
const defaultContextValue: LanguageContextType = {
  language: 'ru',
  setLanguage: () => {},
  t: defaultT,
};

// Create context with default value to prevent HMR issues
const LanguageContext = createContext<LanguageContextType>(defaultContextValue);

// Prevent context recreation during HMR
if (import.meta.hot) {
  import.meta.hot.accept();
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'ru';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  return useContext(LanguageContext);
};
